vim.o.termguicolors = true
local h = vim.api.nvim_set_hl
h(0, "OctoBubbleDelimiterGrey", { fg = "#191724" })
h(0, "OctoBubbleGreen", { bg = "#75B087", fg = "#191724" })
h(0, "OctoBubbleDelimiterGreen", { fg = "#75B087" })
h(0, "OctoBubbleBlue", { bg = "#5EB1AF", fg = "#191724" })
h(0, "OctoBubbleDelimiterBlue", { fg = "#5EB1AF" })
h(0, "OctoBubbleYellow", { bg = "#C7B96F", fg = "#191724" })
h(0, "OctoBubbleDelimiterYellow", { fg = "#C7B96F" })
h(0, "OctoBubbleRed", { bg = "#DF8BA0", fg = "#191724" })
h(0, "OctoBubbleDelimiterRed", { fg = "#DF8BA0" })
h(0, "OctoBubblePurple", { bg = "#A19DD4", fg = "#191724" })
h(0, "FzfLuaNormal", { link = "NormalFloat" })
h(0, "FzfLuaBorder", { link = "FloatBorder" })
h(0, "FzfLuaTitle", { link = "FloatTitle" })
h(0, "FzfLuaHeaderBind", { fg = "#C7B96F" })
h(0, "FzfLuaHeaderText", { fg = "#C79A76" })
h(0, "FzfLuaDirPart", { link = "NonText" })
h(0, "FzfLuaFzfMatch", { fg = "#7AA8CE" })
h(0, "FzfLuaFzfPrompt", { fg = "#7AA8CE" })
h(0, "FzfLuaPathColNr", { fg = "#7AA8CE" })
h(0, "FzfLuaPathLineNr", { fg = "#75B087" })
h(0, "FzfLuaBufName", { fg = "#A19DD4" })
h(0, "FzfLuaBufNr", { fg = "#C7B96F" })
h(0, "FzfLuaBufFlagCur", { fg = "#C79A76" })
h(0, "FzfLuaBufFlagAlt", { fg = "#7AA8CE" })
h(0, "FzfLuaTabTitle", { fg = "#5EB1AF" })
h(0, "FzfLuaTabMarker", { fg = "#C7B96F" })
h(0, "FzfLuaLiveSym", { fg = "#C79A76" })
h(0, "OctoStatePendingFloat", { bg = "#191724", fg = "#C79A76" })
h(0, "OctoStateApproved", { link = "OctoStateOpen" })
h(0, "OctoStateApprovedFloat", { link = "OctoStateOpen" })
h(0, "OctoStateChangesRequested", { bg = "#191724", fg = "#DF8BA0" })
h(0, "OctoStateChangesRequestedFloat", { bg = "#191724", fg = "#DF8BA0" })
h(0, "OctoStateCommented", { link = "Normal" })
h(0, "OctoStateCommentedFloat", { link = "Normal" })
h(0, "OctoStateDismissed", { link = "OctoStateClosed" })
h(0, "OctoStateDismissedFloat", { link = "OctoStateClosed" })
h(0, "OctoStateSubmittedBubble", { link = "OctoBubbleGreen" })
h(0, "GitGraphHash", { fg = "#A19DD4" })
h(0, "GitGraphTimestamp", { fg = "#7AA8CE" })
h(0, "GitGraphAuthor", { fg = "#C394C2" })
h(0, "GitGraphBranchName", { fg = "#5EB1AF" })
h(0, "GitGraphBranchTag", { fg = "#A19DD4" })
h(0, "GitGraphBranchMsg", { fg = "#7D7D7D" })
h(0, "GitGraphBranch1", { fg = "#C7B96F" })
h(0, "GitGraphBranch2", { fg = "#A19DD4" })
h(0, "GitGraphBranch3", { fg = "#5EB1AF" })
h(0, "GitGraphBranch4", { fg = "#75B087" })
h(0, "GitGraphBranch5", { fg = "#DF8BA0" })
h(0, "OctoReviewDiffDeleteText", { bg = "#543A49" })
h(0, "DapUIPlayPause", { fg = "#75B087" })
h(0, "DapUIPlayPauseNC", { link = "DapUIPlayPause" })
h(0, "DapUIRestart", { fg = "#75B087" })
h(0, "DapUIRestartNC", { link = "DapUIRestart" })
h(0, "DapUIUnavailableNC", { link = "DapUIUnavailable" })
h(0, "DapUIWinSelect", { fg = "#C79A76" })
h(0, "DiagnosticSignOk", { fg = "#75B087" })
h(0, "LspDiagnosticsDefaultError", { fg = "#DF8BA0" })
h(0, "LspDiagnosticsDefaultWarning", { fg = "#C7B96F" })
h(0, "LspDiagnosticsDefaultInformation", { fg = "#5EB1AF" })
h(0, "LspDiagnosticsDefaultHint", { fg = "#5EB1AF" })
h(0, "LspSignatureActiveParameter", { bg = "#37363E", bold = true })
h(0, "OverseerPENDING", {  })
h(0, "GitSignsDelete", { fg = "#DF8BA0" })
h(0, "OverseerRUNNING", { fg = "#C7B96F" })
h(0, "OverseerSUCCESS", { fg = "#75B087" })
h(0, "OverseerCANCELED", { fg = "#7D7D7D" })
h(0, "OverseerFAILURE", { fg = "#DF8BA0" })
h(0, "OverseerTask", { fg = "#7AA8CE" })
h(0, "OverseerTaskBorder", { fg = "#5EB1AF" })
h(0, "OverseerOutput", { fg = "#A2A2A9" })
h(0, "OverseerComponent", { fg = "#C7B96F" })
h(0, "OverseerField", { fg = "#75B087" })
h(0, "LspDiagnosticsUnderlineHint", { sp = "#5EB1AF", underline = true })
h(0, "LspCodeLens", { fg = "#84848C" })
h(0, "LspCodeLensSeparator", { link = "LspCodeLens" })
h(0, "LspInfoBorder", { link = "FloatBorder" })
h(0, "Added", { fg = "#75B087" })
h(0, "PounceMatch", { bg = "#9EC8AB", bold = true, fg = "#191724" })
h(0, "PounceGap", { bg = "#527B5F", bold = true, fg = "#191724" })
h(0, "PounceAccept", { bg = "#C79A76", bold = true, fg = "#191724" })
h(0, "PounceAcceptBest", { bg = "#5EB1AF", bold = true, fg = "#191724" })
h(0, "GitSignsAddPreview", { link = "DiffAdd" })
h(0, "DiffAdd", { bg = "#2A3336" })
h(0, "RainbowDelimiterRed", { fg = "#DF8BA0" })
h(0, "RainbowDelimiterYellow", { fg = "#C7B96F" })
h(0, "RainbowDelimiterBlue", { fg = "#7AA8CE" })
h(0, "RainbowDelimiterOrange", { fg = "#C79A76" })
h(0, "RainbowDelimiterGreen", { fg = "#75B087" })
h(0, "RainbowDelimiterViolet", { fg = "#A19DD4" })
h(0, "RainbowDelimiterCyan", { fg = "#5EB1AF" })
h(0, "Conditional", { italic = true, fg = "#A19DD4" })
h(0, "Repeat", { fg = "#A19DD4" })
h(0, "Label", { fg = "#5EB1AF" })
h(0, "PreProc", { fg = "#A19DD4" })
h(0, "Include", { fg = "#A19DD4" })
h(0, "Define", { link = "PreProc" })
h(0, "Macro", { fg = "#A19DD4" })
h(0, "PreCondit", { link = "PreProc" })
h(0, "StorageClass", { fg = "#C7B96F" })
h(0, "Structure", { fg = "#C7B96F" })
h(0, "RenderMarkdownCode", { bg = "#0B0A0F" })
h(0, "RenderMarkdownCodeInline", { bg = "#37363E" })
h(0, "RenderMarkdownBullet", { fg = "#5EB1AF" })
h(0, "RenderMarkdownTableHead", { fg = "#7AA8CE" })
h(0, "RenderMarkdownTableRow", { fg = "#7AA8CE" })
h(0, "RenderMarkdownSuccess", { fg = "#75B087" })
h(0, "RenderMarkdownInfo", { fg = "#5EB1AF" })
h(0, "RenderMarkdownHint", { fg = "#5EB1AF" })
h(0, "RenderMarkdownWarn", { fg = "#C7B96F" })
h(0, "RenderMarkdownError", { fg = "#DF8BA0" })
h(0, "htmlH1", { bold = true, fg = "#A19DD4" })
h(0, "htmlH2", { bold = true, fg = "#7AA8CE" })
h(0, "mkdCodeDelimiter", { bg = "#191724", fg = "#A2A2A9" })
h(0, "mkdCodeStart", { bold = true, fg = "#C394C2" })
h(0, "mkdCodeEnd", { bold = true, fg = "#C394C2" })
h(0, "debugPC", { bg = "#0B0A0F" })
h(0, "debugBreakpoint", { bg = "#191724", fg = "#84848C" })
h(0, "illuminatedWord", { bg = "#37363E" })
h(0, "illuminatedCurWord", { bg = "#37363E" })
h(0, "diffAdded", { fg = "#75B087" })
h(0, "diffRemoved", { fg = "#DF8BA0" })
h(0, "SnacksNormal", { link = "Normal" })
h(0, "SnacksWinBar", { link = "Title" })
h(0, "SnacksBackdrop", { link = "FloatShadow" })
h(0, "SnacksNormalNC", { link = "NormalFloat" })
h(0, "SnacksWinBarNC", { link = "SnacksWinBar" })
h(0, "SnacksNotifierInfo", { fg = "#7AA8CE" })
h(0, "SnacksNotifierIconInfo", { fg = "#7AA8CE" })
h(0, "SnacksNotifierTitleInfo", { italic = true, fg = "#7AA8CE" })
h(0, "SnacksNotifierFooterInfo", { link = "DiagnosticInfo" })
h(0, "SnacksNotifierBorderInfo", { fg = "#7AA8CE" })
h(0, "SnacksNotifierWarn", { fg = "#C7B96F" })
h(0, "SnacksNotifierIconWarn", { fg = "#C7B96F" })
h(0, "SnacksNotifierTitleWarn", { italic = true, fg = "#C7B96F" })
h(0, "SnacksNotifierBorderWarn", { fg = "#C7B96F" })
h(0, "SnacksNotifierFooterWarn", { link = "DiagnosticWarn" })
h(0, "SnacksNotifierDebug", { fg = "#C79A76" })
h(0, "SnacksNotifierIconDebug", { fg = "#C79A76" })
h(0, "SnacksNotifierTitleDebug", { italic = true, fg = "#C79A76" })
h(0, "SnacksNotifierBorderDebug", { fg = "#C79A76" })
h(0, "SnacksNotifierFooterDebug", { link = "DiagnosticHint" })
h(0, "SnacksNotifierError", { fg = "#DF8BA0" })
h(0, "SnacksNotifierIconError", { fg = "#DF8BA0" })
h(0, "SnacksNotifierTitleError", { italic = true, fg = "#DF8BA0" })
h(0, "SnacksNotifierBorderError", { fg = "#DF8BA0" })
h(0, "SnacksNotifierFooterError", { link = "DiagnosticError" })
h(0, "SnacksNotifierTrace", { fg = "#C394C2" })
h(0, "SnacksNotifierIconTrace", { fg = "#C394C2" })
h(0, "SnacksNotifierTitleTrace", { italic = true, fg = "#C394C2" })
h(0, "SnacksNotifierBorderTrace", { fg = "#C394C2" })
h(0, "SnacksNotifierFooterTrace", { link = "DiagnosticHint" })
h(0, "SnacksDashboardNormal", { link = "Normal" })
h(0, "SnacksDashboardDesc", { fg = "#7AA8CE" })
h(0, "SnacksDashboardFile", { fg = "#7AA8CE" })
h(0, "SnacksDashboardDir", { link = "NonText" })
h(0, "SnacksDashboardFooter", { italic = true, fg = "#C7B96F" })
h(0, "SnacksDashboardHeader", { fg = "#7AA8CE" })
h(0, "SnacksDashboardIcon", { bold = true, fg = "#A19DD4" })
h(0, "SnacksDashboardKey", { fg = "#C79A76" })
h(0, "SnacksDashboardTerminal", { link = "SnacksDashboardNormal" })
h(0, "SnacksDashboardSpecial", { link = "Special" })
h(0, "SnacksDashboardTitle", { link = "Title" })
h(0, "SnacksIndentScope", { fg = "#7D7D7D" })
h(0, "SnacksPickerSelected", { bg = "#37363E", bold = true, fg = "#A2A2A9" })
h(0, "SnacksPickerMatch", { fg = "#7AA8CE" })
h(0, "SnacksPicker", { link = "NormalFloat" })
h(0, "SnacksPickerBorder", { link = "FloatBorder" })
h(0, "SnacksPickerInputBorder", { link = "SnacksPickerBorder" })
h(0, "SnacksPickerInput", { link = "NormalFloat" })
h(0, "SnacksPickerPrompt", { fg = "#C394C2" })
h(0, "tkLink", { fg = "#7AA8CE" })
h(0, "tkBrackets", { fg = "#A19DD4" })
h(0, "tkTag", { fg = "#5EB1AF" })
h(0, "GrugFarResultsMatch", { link = "IncSearch" })
h(0, "HarpoonWindow", { bg = "#191724", fg = "#A2A2A9" })
h(0, "HarpoonBorder", { fg = "#7AA8CE" })
h(0, "Dash", { bold = true, fg = "#7D7D7D" })
h(0, "Quote", { link = "@markup.strong" })
h(0, "CodeBlock", { bg = "#0B0A0F" })
h(0, "Headline", { link = "Headline1" })
h(0, "Headline1", { bg = "#37363E", fg = "#DF8BA0" })
h(0, "Headline2", { bg = "#37363E", fg = "#C79A76" })
h(0, "Headline3", { bg = "#37363E", fg = "#C7B96F" })
h(0, "Headline4", { bg = "#37363E", fg = "#75B087" })
h(0, "IlluminatedWordWrite", { bg = "#2E2D36", standout = true })
h(0, "Headline6", { bg = "#37363E", fg = "#7AA8CE" })
h(0, "HopNextKey", { bg = "#191724", underline = true, bold = true, fg = "#C79A76" })
h(0, "HopNextKey1", { bg = "#191724", bold = true, fg = "#7AA8CE" })
h(0, "HopNextKey2", { bg = "#191724", italic = true, bold = true, fg = "#5EB1AF" })
h(0, "HopUnmatched", { bg = "#191724", fg = "#84848C" })
h(0, "MiniIconsPurple", { fg = "#A19DD4" })
h(0, "MiniIconsRed", { fg = "#DF8BA0" })
h(0, "MiniIconsYellow", { fg = "#C7B96F" })
h(0, "MiniIndentscopeSymbol", { fg = "#7D7D7D" })
h(0, "MiniJump", { bg = "#A19DD4", fg = "#7D7D7D" })
h(0, "MiniJump2dDim", { fg = "#84848C" })
h(0, "MiniJump2dSpot", { bg = "#191724", underline = true, bold = true, fg = "#C79A76" })
h(0, "MiniJump2dSpotAhead", { bg = "#0D0C12", fg = "#5EB1AF" })
h(0, "MiniJump2dSpotUnique", { bg = "#191724", bold = true, fg = "#5EB1AF" })
h(0, "MiniMapNormal", { link = "NormalFloat" })
h(0, "MiniMapSymbolCount", { link = "Special" })
h(0, "MiniMapSymbolLine", { link = "Title" })
h(0, "MiniMapSymbolView", { link = "Delimiter" })
h(0, "MiniNotifyBorder", { link = "FloatBorder" })
h(0, "MiniNotifyNormal", { link = "NormalFloat" })
h(0, "MiniNotifyTitle", { link = "FloatTitle" })
h(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
h(0, "MiniPickBorder", { link = "FloatBorder" })
h(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
h(0, "MiniPickBorderText", { bg = "#0B0A0F", fg = "#A19DD4" })
h(0, "MiniPickIconDirectory", { link = "Directory" })
h(0, "MiniPickIconFile", { link = "MiniPickNormal" })
h(0, "MiniPickNormal", { link = "NormalFloat" })
h(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
h(0, "MiniPickMatchCurrent", { bg = "#37363E", bold = true, fg = "#C394C2" })
h(0, "MiniPickMatchMarked", { link = "Visual" })
h(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
h(0, "MiniPickPreviewLine", { link = "CursorLine" })
h(0, "MiniPickPreviewRegion", { link = "IncSearch" })
h(0, "MiniPickPrompt", { bg = "#0B0A0F", fg = "#A2A2A9" })
h(0, "MiniPickPromptCaret", { bg = "#0B0A0F", fg = "#C394C2" })
h(0, "MiniPickPromptPrefix", { bg = "#0B0A0F", fg = "#C394C2" })
h(0, "MiniStarterCurrent", {  })
h(0, "MiniStarterFooter", { italic = true, fg = "#C7B96F" })
h(0, "MiniStarterHeader", { fg = "#7AA8CE" })
h(0, "MiniStarterInactive", { italic = true, fg = "#7C7992" })
h(0, "MiniStarterItem", { fg = "#A2A2A9" })
h(0, "MiniStarterItemBullet", { fg = "#7AA8CE" })
h(0, "MiniStarterItemPrefix", { fg = "#A19DD4" })
h(0, "MiniStarterSection", { fg = "#C394C2" })
h(0, "MiniStarterQuery", { fg = "#75B087" })
h(0, "MiniStatuslineDevinfo", { bg = "#37363E", fg = "#878794" })
h(0, "MiniStatuslineFileinfo", { bg = "#37363E", fg = "#878794" })
h(0, "MiniStatuslineFilename", { bg = "#0B0A0F", fg = "#A2A2A9" })
h(0, "MiniStatuslineInactive", { bg = "#0B0A0F", fg = "#7AA8CE" })
h(0, "MiniStatuslineModeCommand", { bg = "#C79A76", bold = true, fg = "#191724" })
h(0, "MiniStatuslineModeInsert", { bg = "#75B087", bold = true, fg = "#191724" })
h(0, "MiniStatuslineModeNormal", { bg = "#7AA8CE", bold = true, fg = "#0B0A0F" })
h(0, "MiniStatuslineModeOther", { bg = "#5EB1AF", bold = true, fg = "#191724" })
h(0, "MiniStatuslineModeReplace", { bg = "#DF8BA0", bold = true, fg = "#191724" })
h(0, "MiniStatuslineModeVisual", { bg = "#A19DD4", bold = true, fg = "#191724" })
h(0, "MiniSurround", { bg = "#A19DD4", fg = "#37363E" })
h(0, "MiniTablineCurrent", { bg = "#191724", sp = "#DF8BA0", italic = true, underline = true, bold = true, fg = "#A2A2A9" })
h(0, "MiniTablineFill", { bg = "#191724" })
h(0, "MiniTablineHidden", { bg = "#0B0A0F", fg = "#A2A2A9" })
h(0, "MiniTablineModifiedCurrent", { bg = "NONE", italic = true, bold = true, fg = "#DF8BA0" })
h(0, "MiniTablineModifiedHidden", { bg = "NONE", fg = "#DF8BA0" })
h(0, "MiniTablineModifiedVisible", { bg = "NONE", fg = "#DF8BA0" })
h(0, "MiniTablineTabpagesection", { bg = "#191724", fg = "#37363E" })
h(0, "MiniTablineVisible", { bg = "NONE" })
h(0, "MiniTestEmphasis", { bold = true })
h(0, "MiniTestFail", { bold = true, fg = "#DF8BA0" })
h(0, "MiniTestPass", { bold = true, fg = "#75B087" })
h(0, "MiniTrailspace", { bg = "#DF8BA0" })
h(0, "@lsp.type.enumMember", { fg = "#5EB1AF" })
h(0, "@lsp.type.variable", {  })
h(0, "TelescopeBorder", { link = "FloatBorder" })
h(0, "TelescopeNormal", { link = "NormalFloat" })
h(0, "TelescopePreviewNormal", { link = "TelescopeNormal" })
h(0, "TelescopePromptNormal", { link = "TelescopeNormal" })
h(0, "TelescopeResultsNormal", { link = "TelescopeNormal" })
h(0, "TelescopeTitle", { link = "FloatTitle" })
h(0, "TelescopeSelectionCaret", { bg = "#37363E", fg = "#C394C2" })
h(0, "TelescopeSelection", { bg = "#37363E", bold = true, fg = "#C394C2" })
h(0, "TelescopeMatching", { fg = "#7AA8CE" })
h(0, "TelescopePromptPrefix", { fg = "#C394C2" })
h(0, "TreesitterContext", { bg = "#0B0A0F", fg = "#A2A2A9" })
h(0, "TreesitterContextBottom", { sp = "#37363E", underline = true })
h(0, "rainbowcol1", { fg = "#DF8BA0" })
h(0, "rainbowcol2", { fg = "#5EB1AF" })
h(0, "rainbowcol3", { fg = "#C7B96F" })
h(0, "rainbowcol4", { fg = "#7AA8CE" })
h(0, "rainbowcol5", { fg = "#A19DD4" })
h(0, "rainbowcol6", { fg = "#C394C2" })
h(0, "rainbowcol7", { fg = "#75B087" })
h(0, "TSRainbowRed", { fg = "#DF8BA0" })
h(0, "TSRainbowYellow", { fg = "#C7B96F" })
h(0, "TSRainbowBlue", { fg = "#7AA8CE" })
h(0, "TSRainbowOrange", { fg = "#C79A76" })
h(0, "TSRainbowGreen", { fg = "#75B087" })
h(0, "TSRainbowViolet", { fg = "#A19DD4" })
h(0, "TSRainbowCyan", { fg = "#5EB1AF" })
h(0, "UfoFoldedFg", { fg = "#7AA8CE" })
h(0, "UfoFoldedEllipsis", { bg = "#7AA8CE", fg = "#0B0A0F" })
h(0, "Sneak", { bg = "#A19DD4", fg = "#7D7D7D" })
h(0, "SneakScope", { bg = "#A2A2A9" })
h(0, "WhichKey", { link = "NormalFloat" })
h(0, "WhichKeyBorder", { link = "FloatBorder" })
h(0, "WhichKeyGroup", { fg = "#7AA8CE" })
h(0, "WhichKeySeparator", { fg = "#84848C" })
h(0, "WhichKeyDesc", { fg = "#A19DD4" })
h(0, "WhichKeyValue", { fg = "#84848C" })
h(0, "WindowPickerStatusLine", { bold = true, fg = "#DF8BA0" })
h(0, "WindowPickerStatusLineNC", { bold = true, fg = "#DF8BA0" })
h(0, "WindowPickerWinBar", { bold = true, fg = "#DF8BA0" })
h(0, "WindowPickerWinBarNC", { bold = true, fg = "#DF8BA0" })
h(0, "Float", { link = "Number" })
h(0, "DropBarMenuHoverEntry", { link = "Visual" })
h(0, "DropBarMenuHoverIcon", { reverse = true })
h(0, "DropBarMenuHoverSymbol", { bold = true })
h(0, "DropBarIconUISeparator", { fg = "#808084" })
h(0, "DropBarKindArray", { fg = "#A2A2A9" })
h(0, "DropBarKindBoolean", { fg = "#A2A2A9" })
h(0, "DropBarKindBreakStatement", { fg = "#A2A2A9" })
h(0, "DropBarKindCall", { fg = "#A2A2A9" })
h(0, "DropBarKindCaseStatement", { fg = "#A2A2A9" })
h(0, "DropBarKindClass", { fg = "#A2A2A9" })
h(0, "DropBarKindConstant", { fg = "#A2A2A9" })
h(0, "DropBarKindConstructor", { fg = "#A2A2A9" })
h(0, "DropBarKindContinueStatement", { fg = "#A2A2A9" })
h(0, "DropBarKindDeclaration", { fg = "#A2A2A9" })
h(0, "DropBarKindDelete", { fg = "#A2A2A9" })
h(0, "DropBarKindDoStatement", { fg = "#A2A2A9" })
h(0, "DropBarKindElseStatement", { fg = "#A2A2A9" })
h(0, "DropBarKindEnum", { fg = "#A2A2A9" })
h(0, "DropBarKindEnumMember", { fg = "#A2A2A9" })
h(0, "DropBarKindEvent", { fg = "#A2A2A9" })
h(0, "DropBarKindField", { fg = "#A2A2A9" })
h(0, "DropBarKindFile", { fg = "#A2A2A9" })
h(0, "DropBarKindFolder", { fg = "#A2A2A9" })
h(0, "DropBarKindForStatement", { fg = "#A2A2A9" })
h(0, "NvimTreeOpenedFolderName", { fg = "#7AA8CE" })
h(0, "NvimTreeEmptyFolderName", { fg = "#7AA8CE" })
h(0, "NvimTreeIndentMarker", { fg = "#84848C" })
h(0, "NvimTreeWinSeparator", { bg = "#191724", fg = "#191724" })
h(0, "NvimTreeRootFolder", { bold = true, fg = "#7AA8CE" })
h(0, "DropBarKindIfStatement", { fg = "#A2A2A9" })
h(0, "NvimTreeStatuslineNc", { bg = "#0B0A0F", fg = "#0B0A0F" })
h(0, "NvimTreeGitDirty", { fg = "#C7B96F" })
h(0, "NvimTreeGitNew", { fg = "#7AA8CE" })
h(0, "DropBarKindKeyword", { fg = "#A2A2A9" })
h(0, "DropBarKindList", { fg = "#A2A2A9" })
h(0, "DropBarKindMacro", { fg = "#A2A2A9" })
h(0, "DropBarKindMarkdownH1", { fg = "#A2A2A9" })
h(0, "DropBarKindMarkdownH2", { fg = "#A2A2A9" })
h(0, "DropBarKindMarkdownH3", { fg = "#A2A2A9" })
h(0, "DropBarKindMarkdownH4", { fg = "#A2A2A9" })
h(0, "DropBarKindMarkdownH5", { fg = "#A2A2A9" })
h(0, "DropBarKindMarkdownH6", { fg = "#A2A2A9" })
h(0, "DropBarKindMethod", { fg = "#A2A2A9" })
h(0, "DropBarKindModule", { fg = "#A2A2A9" })
h(0, "DropBarKindNamespace", { fg = "#A2A2A9" })
h(0, "Debug", { link = "Special" })
h(0, "Changed", { fg = "#7AA8CE" })
h(0, "Function", { fg = "#7AA8CE" })
h(0, "BlinkCmpLabelDeprecated", { strikethrough = true, fg = "#84848C" })
h(0, "BlinkCmpLabel", { fg = "#7D7D7D" })
h(0, "BlinkCmpLabelDetail", { link = "PmenuExtra" })
h(0, "BlinkCmpLabelMatch", { link = "PmenuMatch" })
h(0, "BlinkCmpLabelDescription", { link = "PmenuExtra" })
h(0, "Constant", { fg = "#C79A76" })
h(0, "Operator", { fg = "#5EB1AF" })
h(0, "MarkviewPalette6", { bg = "#222534", fg = "#7AA8CE" })
h(0, "MarkviewPalette6Fg", { fg = "#7AA8CE" })
h(0, "MarkviewPalette6Bg", { bg = "#222534" })
h(0, "MarkviewIcon6", { bg = "#0B0A0F", fg = "#7AA8CE" })
h(0, "MarkviewPalette7", { bg = "#262435", fg = "#A19DD4" })
h(0, "MarkviewPalette7Fg", { fg = "#A19DD4" })
h(0, "MarkviewPalette7Bg", { bg = "#262435" })
h(0, "MarkviewIcon7", { bg = "#0B0A0F", fg = "#A19DD4" })
h(0, "MasonHeader", { bg = "#7AA8CE", bold = true, fg = "#191724" })
h(0, "MasonHeaderSecondary", { bg = "#7AA8CE", bold = true, fg = "#191724" })
h(0, "MasonHighlight", { fg = "#75B087" })
h(0, "MasonHighlightBlock", { bg = "#75B087", fg = "#191724" })
h(0, "MasonHighlightBlockBold", { bg = "#7AA8CE", bold = true, fg = "#191724" })
h(0, "MasonHighlightSecondary", { fg = "#A19DD4" })
h(0, "MasonHighlightBlockSecondary", { bg = "#7AA8CE", fg = "#191724" })
h(0, "MasonHighlightBlockBoldSecondary", { bg = "#7AA8CE", bold = true, fg = "#191724" })
h(0, "MasonMuted", { fg = "#84848C" })
h(0, "MasonMutedBlock", { bg = "#84848C", fg = "#191724" })
h(0, "MasonMutedBlockBold", { bg = "#C7B96F", bold = true, fg = "#191724" })
h(0, "MasonError", { fg = "#DF8BA0" })
h(0, "MasonHeading", { bold = true, fg = "#7AA8CE" })
h(0, "MiniAnimateCursor", { reverse = true, nocombine = true })
h(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
h(0, "MiniClueBorder", { link = "FloatBorder" })
h(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
h(0, "MiniClueDescSingle", { link = "NormalFloat" })
h(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
h(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
h(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
h(0, "MiniClueTitle", { link = "FloatTitle" })
h(0, "MiniCompletionActiveParameter", { underline = true })
h(0, "MiniCursorword", { underline = true })
h(0, "MiniCursorwordCurrent", { underline = true })
h(0, "MiniDepsChangeAdded", { link = "diffAdded" })
h(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
h(0, "MiniDepsHint", { link = "DiagnosticHint" })
h(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
h(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
h(0, "MiniDepsPlaceholder", { link = "Comment" })
h(0, "MiniDepsTitle", { link = "Title" })
h(0, "MiniDepsTitleError", { bg = "#DF8BA0", fg = "#191724" })
h(0, "MiniDepsTitleSame", { link = "DiffText" })
h(0, "MiniDepsTitleUpdate", { bg = "#75B087", fg = "#191724" })
h(0, "MiniDiffSignAdd", { fg = "#75B087" })
h(0, "MiniDiffSignChange", { fg = "#C7B96F" })
h(0, "MiniDiffSignDelete", { fg = "#DF8BA0" })
h(0, "MiniDiffOverAdd", { link = "DiffAdd" })
h(0, "MiniDiffOverChange", { link = "DiffText" })
h(0, "MiniDiffOverContext", { link = "DiffChange" })
h(0, "MiniDiffOverDelete", { link = "DiffDelete" })
h(0, "MiniFilesBorder", { link = "FloatBorder" })
h(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
h(0, "MiniFilesCursorLine", { link = "CursorLine" })
h(0, "MiniFilesDirectory", { link = "Directory" })
h(0, "MiniFilesFile", { fg = "#A2A2A9" })
h(0, "MiniFilesNormal", { link = "NormalFloat" })
h(0, "MiniFilesTitle", { link = "FloatTitle" })
h(0, "MiniFilesTitleFocused", { bg = "#0B0A0F", bold = true, fg = "#878794" })
h(0, "MiniHipatternsFixme", { bg = "#DF8BA0", bold = true, fg = "#191724" })
h(0, "MiniHipatternsHack", { bg = "#C7B96F", bold = true, fg = "#191724" })
h(0, "MiniHipatternsNote", { bg = "#5EB1AF", bold = true, fg = "#191724" })
h(0, "MiniHipatternsTodo", { bg = "#5EB1AF", bold = true, fg = "#191724" })
h(0, "MiniIconsAzure", { fg = "#5EB1AF" })
h(0, "MiniIconsBlue", { fg = "#7AA8CE" })
h(0, "MiniIconsCyan", { fg = "#5EB1AF" })
h(0, "MiniIconsGreen", { fg = "#75B087" })
h(0, "MiniIconsGrey", { fg = "#A2A2A9" })
h(0, "MiniIconsOrange", { fg = "#C79A76" })
h(0, "GitSignsDeletePreview", { link = "DiffDelete" })
h(0, "DiffDelete", { bg = "#3D2C3A" })
h(0, "GitSignsCurrentLineBlame", { fg = "#7C7992" })
h(0, "NonText", { fg = "#84848C" })
h(0, "GitSignsAddInline", { bg = "#3A4E48" })
h(0, "TermCursor", { bg = "#C394C2", fg = "#191724" })
h(0, "GitSignsDeleteInline", { bg = "#604151" })
h(0, "GitSignsChangeInline", { bg = "#272B3C" })
h(0, "LspReferenceText", { bg = "#37363E" })
h(0, "LspReferenceRead", { bg = "#37363E" })
h(0, "LspReferenceWrite", { bg = "#37363E" })
h(0, "Normal", { bg = "#191724", fg = "#A2A2A9" })
h(0, "GitGutterAdd", { fg = "#75B087" })
h(0, "SignifySignAdd", { fg = "#75B087" })
h(0, "GitGutterChange", { fg = "#C7B96F" })
h(0, "SignifySignChange", { fg = "#C7B96F" })
h(0, "DiffChange", { bg = "#202130" })
h(0, "GitGutterDelete", { fg = "#DF8BA0" })
h(0, "SignifySignDelete", { fg = "#DF8BA0" })
h(0, "GitGutterAddLineNr", { fg = "#75B087" })
h(0, "GitGutterChangeLineNr", { fg = "#C7B96F" })
h(0, "GitGutterDeleteLineNr", { fg = "#DF8BA0" })
h(0, "DiagnosticVirtualTextWarn", { bg = "#2A262B", italic = true, fg = "#C7B96F" })
h(0, "MarkviewBlockQuoteDefault", { bg = "#0B0A0F", fg = "#7D7D7D" })
h(0, "MarkviewBlockQuoteError", { bg = "#1F161D", fg = "#DF8BA0" })
h(0, "MarkviewBlockQuoteNote", { bg = "#161921", fg = "#7AA8CE" })
h(0, "MarkviewBlockQuoteOk", { bg = "#151A1A", fg = "#75B087" })
h(0, "MarkviewBlockQuoteSpecial", { bg = "#191822", fg = "#A19DD4" })
h(0, "MarkviewBlockQuoteWarn", { bg = "#1D1B18", fg = "#C7B96F" })
h(0, "MarkviewHyperlink", { link = "@markup.link.url" })
h(0, "MarkviewCode", { bg = "#0B0A0F" })
h(0, "MarkviewCodeFg", { fg = "#0B0A0F" })
h(0, "MarkviewCodeInfo", { bg = "#0B0A0F", fg = "#7D7D7D" })
h(0, "MarkviewInlineCode", { bg = "#37363E" })
h(0, "MarkviewTableHeader", { fg = "#7AA8CE" })
h(0, "MarkviewPalette0", { bg = "#23212C", fg = "#7D7D7D" })
h(0, "MarkviewPalette0Fg", { fg = "#7D7D7D" })
h(0, "MarkviewPalette0Bg", { bg = "#23212C" })
h(0, "MarkviewIcon0", { bg = "#0B0A0F", fg = "#7D7D7D" })
h(0, "MarkviewPalette1", { bg = "#2C2230", fg = "#DF8BA0" })
h(0, "MarkviewPalette1Fg", { fg = "#DF8BA0" })
h(0, "MarkviewPalette1Bg", { bg = "#2C2230" })
h(0, "MarkviewIcon1", { bg = "#0B0A0F", fg = "#DF8BA0" })
h(0, "MarkviewPalette2", { bg = "#2A232C", fg = "#C79A76" })
h(0, "MarkviewPalette2Fg", { fg = "#C79A76" })
h(0, "MarkviewPalette2Bg", { bg = "#2A232C" })
h(0, "MarkviewIcon2", { bg = "#0B0A0F", fg = "#C79A76" })
h(0, "MarkviewPalette3", { bg = "#2A262B", fg = "#C7B96F" })
h(0, "MarkviewPalette3Fg", { fg = "#C7B96F" })
h(0, "MarkviewPalette3Bg", { bg = "#2A262B" })
h(0, "MarkviewIcon3", { bg = "#0B0A0F", fg = "#C7B96F" })
h(0, "MarkviewPalette4", { bg = "#22262D", fg = "#75B087" })
h(0, "MarkviewPalette4Fg", { fg = "#75B087" })
h(0, "MarkviewPalette4Bg", { bg = "#22262D" })
h(0, "MarkviewIcon4", { bg = "#0B0A0F", fg = "#75B087" })
h(0, "MarkviewPalette5", { bg = "#202631", fg = "#5EB1AF" })
h(0, "MarkviewPalette5Fg", { fg = "#5EB1AF" })
h(0, "MarkviewPalette5Bg", { bg = "#202631" })
h(0, "MarkviewIcon5", { bg = "#0B0A0F", fg = "#5EB1AF" })
h(0, "Title", { bold = true, fg = "#7AA8CE" })
h(0, "MoreMsg", { fg = "#7AA8CE" })
h(0, "ErrorMsg", { italic = true, bold = true, fg = "#DF8BA0" })
h(0, "DiffviewFilePanelCounter", { fg = "#A2A2A9" })
h(0, "@variable", { fg = "#A2A2A9" })
h(0, "@variable.builtin", { fg = "#DF8BA0" })
h(0, "@variable.parameter", { fg = "#DF8BA0" })
h(0, "@variable.member", { fg = "#7AA8CE" })
h(0, "@constant", { link = "Constant" })
h(0, "@constant.builtin", { fg = "#C79A76" })
h(0, "@constant.macro", { link = "Macro" })
h(0, "@module", { italic = true, fg = "#C7B96F" })
h(0, "DiffviewFilePanelRootPath", { bold = true, fg = "#7AA8CE" })
h(0, "@label", { link = "Label" })
h(0, "@string", { link = "String" })
h(0, "@string.documentation", { fg = "#5EB1AF" })
h(0, "@string.regexp", { fg = "#A19DD4" })
h(0, "@string.escape", { fg = "#A19DD4" })
h(0, "@string.special", { link = "Special" })
h(0, "@string.special.path", { link = "Special" })
h(0, "@string.special.symbol", { fg = "#C394C2" })
h(0, "@string.special.url", { italic = true, underline = true, fg = "#7AA8CE" })
h(0, "@punctuation.delimiter.regex", { link = "@string.regexp" })
h(0, "@character", { link = "Character" })
h(0, "@character.special", { link = "SpecialChar" })
h(0, "@boolean", { link = "Boolean" })
h(0, "@number", { link = "Number" })
h(0, "@number.float", { link = "Float" })
h(0, "@type", { link = "Type" })
h(0, "@type.builtin", { fg = "#A19DD4" })
h(0, "@type.definition", { link = "Type" })
h(0, "@attribute", { link = "Constant" })
h(0, "@property", { fg = "#7AA8CE" })
h(0, "@function", { link = "Function" })
h(0, "@function.call", { link = "Function" })
h(0, "@function.macro", { fg = "#A19DD4" })
h(0, "@function.method", { link = "Function" })
h(0, "@function.method.call", { link = "Function" })
h(0, "@constructor", { fg = "#C7B96F" })
h(0, "@operator", { link = "Operator" })
h(0, "@keyword", { link = "Keyword" })
h(0, "@keyword.modifier", { link = "Keyword" })
h(0, "@keyword.type", { link = "Keyword" })
h(0, "@keyword.coroutine", { link = "Keyword" })
h(0, "@keyword.function", { fg = "#A19DD4" })
h(0, "@keyword.operator", { fg = "#A19DD4" })
h(0, "@keyword.import", { link = "Include" })
h(0, "@keyword.repeat", { link = "Repeat" })
h(0, "@keyword.return", { fg = "#A19DD4" })
h(0, "@keyword.debug", { link = "Exception" })
h(0, "@keyword.exception", { link = "Exception" })
h(0, "FloatShadowThrough", { bg = "#84848C", blend = 100 })
h(0, "OkMsg", { fg = "#75B087" })
h(0, "SpecialKey", { link = "NonText" })
h(0, "SpellBad", { sp = "#DF8BA0", undercurl = true })
h(0, "BufferInactive", { bg = "#0B0A0F", fg = "#84848C" })
h(0, "LspDiagnosticsUnderlineWarning", { sp = "#C7B96F", underline = true })
h(0, "LspDiagnosticsUnderlineError", { sp = "#DF8BA0", underline = true })
h(0, "LspDiagnosticsVirtualTextHint", { italic = true, fg = "#5EB1AF" })
h(0, "SpellLocal", { sp = "#7AA8CE", undercurl = true })
h(0, "DiagnosticVirtualTextHint", { bg = "#202631", italic = true, fg = "#5EB1AF" })
h(0, "DiagnosticVirtualTextOk", { bg = "#202631", italic = true, fg = "#75B087" })
h(0, "DiagnosticError", { bg = "NONE", italic = true, fg = "#DF8BA0" })
h(0, "DiagnosticWarn", { bg = "NONE", italic = true, fg = "#C7B96F" })
h(0, "DiagnosticInfo", { bg = "NONE", italic = true, fg = "#5EB1AF" })
h(0, "DiagnosticOk", { bg = "NONE", italic = true, fg = "#75B087" })
h(0, "DiagnosticUnderlineError", { sp = "#DF8BA0", underline = true })
h(0, "DiagnosticUnderlineWarn", { sp = "#C7B96F", underline = true })
h(0, "DiagnosticUnderlineInfo", { sp = "#5EB1AF", underline = true })
h(0, "DiagnosticUnderlineHint", { sp = "#5EB1AF", underline = true })
h(0, "DiagnosticUnderlineOk", { sp = "#75B087", underline = true })
h(0, "DiagnosticFloatingError", { fg = "#DF8BA0" })
h(0, "DiagnosticFloatingWarn", { fg = "#C7B96F" })
h(0, "DiagnosticFloatingInfo", { fg = "#5EB1AF" })
h(0, "DiagnosticFloatingHint", { fg = "#5EB1AF" })
h(0, "WarningMsg", { fg = "#C7B96F" })
h(0, "DiagnosticFloatingOk", { fg = "#75B087" })
h(0, "DiagnosticSignError", { fg = "#DF8BA0" })
h(0, "LspInlayHint", { bg = "#2C2B35", fg = "#84848C" })
h(0, "DiagnosticSignWarn", { fg = "#C7B96F" })
h(0, "DiagnosticSignInfo", { fg = "#5EB1AF" })
h(0, "DiagnosticHint", { bg = "NONE", italic = true, fg = "#5EB1AF" })
h(0, "LspDiagnosticsUnderlineInformation", { sp = "#5EB1AF", underline = true })
h(0, "Whitespace", { fg = "#37363E" })
h(0, "LspDiagnosticsVirtualTextInformation", { italic = true, fg = "#5EB1AF" })
h(0, "LspDiagnosticsVirtualTextWarning", { italic = true, fg = "#C7B96F" })
h(0, "LspDiagnosticsVirtualTextError", { italic = true, fg = "#DF8BA0" })
h(0, "LspDiagnosticsHint", { fg = "#5EB1AF" })
h(0, "LspDiagnosticsInformation", { fg = "#5EB1AF" })
h(0, "LspDiagnosticsWarning", { fg = "#C7B96F" })
h(0, "LspDiagnosticsError", { fg = "#DF8BA0" })
h(0, "DiagnosticSignHint", { fg = "#5EB1AF" })
h(0, "WinBarNC", { link = "WinBar" })
h(0, "WinBar", { fg = "#C394C2" })
h(0, "WildMenu", { bg = "#84848C" })
h(0, "VisualNOS", { bg = "#37363E", bold = true })
h(0, "Visual", { bg = "#37363E", bold = true })
h(0, "TermCursorNC", { bg = "#7D7D7D", fg = "#191724" })
h(0, "TabLineSel", { link = "Normal" })
h(0, "TabLineFill", { bg = "#0B0A0F" })
h(0, "TabLine", { bg = "#0B0A0F", fg = "#84848C" })
h(0, "StatusLineNC", { bg = "#0B0A0F", fg = "#37363E" })
h(0, "StatusLine", { bg = "#0B0A0F", fg = "#A2A2A9" })
h(0, "SpellRare", { sp = "#75B087", undercurl = true })
h(0, "DiagnosticVirtualTextInfo", { bg = "#202631", italic = true, fg = "#5EB1AF" })
h(0, "SpellCap", { sp = "#C7B96F", undercurl = true })
h(0, "DiagnosticVirtualTextError", { bg = "#2C2230", italic = true, fg = "#DF8BA0" })
h(0, "Question", { fg = "#7AA8CE" })
h(0, "CurSearch", { bg = "#DF8BA0", fg = "#0B0A0F" })
h(0, "IncSearch", { bg = "#57A2A1", fg = "#0B0A0F" })
h(0, "Search", { bg = "#2E454E", fg = "#A2A2A9" })
h(0, "QuickFixLine", { bg = "#2E2D36", bold = true })
h(0, "ComplHintMore", { link = "Question" })
h(0, "ComplHint", { fg = "#878794" })
h(0, "DiffviewStatusModified", { fg = "#C7B96F" })
h(0, "DiffviewStatusRenamed", { fg = "#C7B96F" })
h(0, "BlinkCmpScrollBarGutter", { bg = "#37363E" })
h(0, "DiffviewStatusCopied", { fg = "#C7B96F" })
h(0, "Beacon", { bg = "#7AA8CE" })
h(0, "DropBarKindInterface", { fg = "#A2A2A9" })
h(0, "IlluminatedWordText", { bg = "#2E2D36" })
h(0, "Headline5", { bg = "#37363E", fg = "#5EB1AF" })
h(0, "PmenuBorder", { bg = "#0B0A0F", fg = "#7AA8CE" })
h(0, "FloatShadow", { bg = "#84848C", blend = 80 })
h(0, "FloatTitle", { bg = "#0B0A0F", fg = "#878794" })
h(0, "FloatBorder", { bg = "#0B0A0F", fg = "#7AA8CE" })
h(0, "NormalFloat", { bg = "#0B0A0F", fg = "#A2A2A9" })
h(0, "NormalSB", { bg = "#0B0A0F", fg = "#A2A2A9" })
h(0, "NormalNC", { bg = "#191724", fg = "#A2A2A9" })
h(0, "MsgSeparator", { link = "WinSeparator" })
h(0, "ModeMsg", { bold = true, fg = "#A2A2A9" })
h(0, "MatchParen", { bg = "#2E2D36", bold = true, fg = "#C79A76" })
h(0, "Substitute", { bg = "#37363E", fg = "#A19DD4" })
h(0, "FoldColumn", { fg = "#84848C" })
h(0, "Folded", { bg = "#37363E", fg = "#7AA8CE" })
h(0, "VertSplit", { fg = "#0B0A0F" })
h(0, "BufferCurrentMod", { bg = "#37363E", fg = "#C7B96F" })
h(0, "AerialEnumIcon", { link = "@type" })
h(0, "AerialFileIcon", { link = "@text.uri" })
h(0, "DiffviewSecondary", { fg = "#75B087" })
h(0, "DiffviewNormal", { bg = "#0B0A0F", fg = "#A2A2A9" })
h(0, "AerialInterfaceIcon", { link = "@type" })
h(0, "AerialStructIcon", { link = "@type" })
h(0, "NvimTreeSymlink", { fg = "#A19DD4" })
h(0, "Tag", { bold = true, fg = "#7AA8CE" })
h(0, "Comment", { italic = true, fg = "#7D7D7D" })
h(0, "Type", { fg = "#C7B96F" })
h(0, "Typedef", { link = "Type" })
h(0, "SpecialChar", { link = "Special" })
h(0, "Delimiter", { fg = "#7D7D7D" })
h(0, "Underlined", { underline = true })
h(0, "Bold", { bold = true })
h(0, "Italic", { italic = true })
h(0, "Todo", { bg = "#C394C2", bold = true, fg = "#191724" })
h(0, "qfLineNr", { fg = "#C7B96F" })
h(0, "qfFileName", { fg = "#7AA8CE" })
h(0, "GlyphPalette9", { fg = "#DF8BA0" })
h(0, "rainbow1", { fg = "#DF8BA0" })
h(0, "rainbow2", { fg = "#C79A76" })
h(0, "rainbow3", { fg = "#C7B96F" })
h(0, "rainbow4", { fg = "#75B087" })
h(0, "rainbow5", { fg = "#5EB1AF" })
h(0, "csvCol1", { fg = "#C79A76" })
h(0, "csvCol2", { fg = "#C7B96F" })
h(0, "csvCol3", { fg = "#75B087" })
h(0, "OctoStateOpen", { bg = "#191724", fg = "#75B087" })
h(0, "DapUIStepOverNC", { link = "DapUIStepOver" })
h(0, "DapUIStepBack", { fg = "#7AA8CE" })
h(0, "DapUIStepBackNC", { link = "DapUIStepBack" })
h(0, "DapUIScope", { fg = "#5EB1AF" })
h(0, "NvimTreeGitDeleted", { fg = "#DF8BA0" })
h(0, "NvimTreeSpecialFile", { fg = "#C394C2" })
h(0, "NavicIconsModule", { bg = "NONE", fg = "#7AA8CE" })
h(0, "BlinkCmpKindModule", { fg = "#7AA8CE" })
h(0, "BlinkCmpKindFile", { fg = "#7AA8CE" })
h(0, "DiffviewStatusUnmerged", { fg = "#C7B96F" })
h(0, "AlphaButtons", { fg = "#7AA8CE" })
h(0, "IlluminatedWordRead", { bg = "#2E2D36" })
h(0, "AerialNullIcon", { link = "@type" })
h(0, "AerialKeyIcon", { link = "@type" })
h(0, "NotifyDEBUGIcon", { fg = "#C79A76" })
h(0, "NotifyDEBUGTitle", { italic = true, fg = "#C79A76" })
h(0, "NotifyTRACEBorder", { fg = "#C394C2" })
h(0, "OctoGreenFloat", { bg = "#191724", fg = "#75B087" })
h(0, "DapBreakpoint", { fg = "#DF8BA0" })
h(0, "DapBreakpointCondition", { fg = "#C7B96F" })
h(0, "DapBreakpointRejected", { fg = "#A19DD4" })
h(0, "@attribute.c_sharp", { fg = "#C7B96F" })
h(0, "DapLogPoint", { fg = "#5EB1AF" })
h(0, "@keyword.import.c", { fg = "#C7B96F" })
h(0, "DapStopped", { fg = "#DF8BA0" })
h(0, "OctoReaction", { link = "OctoBubble" })
h(0, "DapUIVariable", { fg = "#A2A2A9" })
h(0, "@label.yaml", { fg = "#C7B96F" })
h(0, "OctoPullModifications", { fg = "#C79A76" })
h(0, "OctoRedFloat", { bg = "#191724", fg = "#DF8BA0" })
h(0, "OctoPullDeletions", { link = "OctoRed" })
h(0, "LightspeedLabel", { bold = true, underline = true, fg = "#DF8BA0" })
h(0, "OctoNormalFront", { fg = "#A2A2A9" })
h(0, "CmpItemKindTypeParameter", { fg = "#7AA8CE" })
h(0, "@number.css", { fg = "#C79A76" })
h(0, "@string.plain.css", { fg = "#A2A2A9" })
h(0, "DashboardProjectTitle", { fg = "#5EB1AF" })
h(0, "DapUIStepOutNC", { link = "DapUIStepOut" })
h(0, "GlyphPalette1", { fg = "#DF8BA0" })
h(0, "healthWarning", { fg = "#C7B96F" })
h(0, "Keyword", { fg = "#A19DD4" })
h(0, "OctoFilePanelFileName", {  })
h(0, "healthSuccess", { fg = "#5EB1AF" })
h(0, "@lsp.typemod.function.builtin", { link = "@function.builtin" })
h(0, "@function.builtin", { fg = "#C79A76" })
h(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
h(0, "markdownH6", { link = "rainbow6" })
h(0, "markdownH5", { link = "rainbow5" })
h(0, "markdownH4", { link = "rainbow4" })
h(0, "markdownH3", { link = "rainbow3" })
h(0, "markdownH2", { link = "rainbow2" })
h(0, "markdownH1", { link = "rainbow1" })
h(0, "markdownLinkText", { underline = true, fg = "#7AA8CE" })
h(0, "markdownCodeBlock", { fg = "#C394C2" })
h(0, "markdownCode", { fg = "#C394C2" })
h(0, "markdownHeadingDelimiter", { bold = true, fg = "#C79A76" })
h(0, "escCsvCol0", { link = "csvCol0" })
h(0, "csvCol8", { fg = "#A19DD4" })
h(0, "csvCol7", { fg = "#A19DD4" })
h(0, "csvCol6", { fg = "#7AA8CE" })
h(0, "csvCol5", { fg = "#7AA8CE" })
h(0, "csvCol4", { fg = "#5EB1AF" })
h(0, "@method.call.php", { link = "Function" })
h(0, "@method.php", { link = "Function" })
h(0, "@text.title.6.markdown", { link = "rainbow6" })
h(0, "@text.title.5.markdown", { link = "rainbow5" })
h(0, "@text.title.4.markdown", { link = "rainbow4" })
h(0, "@text.title.3.markdown", { link = "rainbow3" })
h(0, "@text.title.2.markdown", { link = "rainbow2" })
h(0, "DapUIFloatBorder", { link = "FloatBorder" })
h(0, "csvCol0", { fg = "#DF8BA0" })
h(0, "rainbow6", { fg = "#7AA8CE" })
h(0, "GitSignsAdd", { fg = "#75B087" })
h(0, "RenderMarkdownH1", { fg = "#DF8BA0" })
h(0, "RenderMarkdownH1Bg", { bg = "#2C2230" })
h(0, "RenderMarkdownH2", { fg = "#C79A76" })
h(0, "RenderMarkdownH2Bg", { bg = "#2A232C" })
h(0, "DapUIThread", { fg = "#75B087" })
h(0, "DapUIStoppedThread", { fg = "#5EB1AF" })
h(0, "DapUISource", { fg = "#7AA8CE" })
h(0, "RenderMarkdownH3", { fg = "#C7B96F" })
h(0, "RenderMarkdownH3Bg", { bg = "#2A262B" })
h(0, "OctoFilePanelTitle", { bold = true, fg = "#7AA8CE" })
h(0, "SagaDetail", { link = "Comment" })
h(0, "GlyphPalette7", { fg = "#A2A2A9" })
h(0, "RenderMarkdownH4", { fg = "#75B087" })
h(0, "RenderMarkdownH4Bg", { bg = "#22262D" })
h(0, "RenderMarkdownH5", { fg = "#5EB1AF" })
h(0, "RenderMarkdownH5Bg", { bg = "#202631" })
h(0, "GlyphPalette6", { fg = "#5EB1AF" })
h(0, "GlyphPalette4", { fg = "#7AA8CE" })
h(0, "GlyphPalette3", { fg = "#C7B96F" })
h(0, "RenderMarkdownH6", { fg = "#7AA8CE" })
h(0, "RenderMarkdownH6Bg", { bg = "#222534" })
h(0, "GlyphPalette2", { fg = "#5EB1AF" })
h(0, "Boolean", { fg = "#C79A76" })
h(0, "Number", { fg = "#C79A76" })
h(0, "String", { fg = "#75B087" })
h(0, "healthError", { fg = "#DF8BA0" })
h(0, "DiffText", { bg = "#364357" })
h(0, "diffIndexLine", { fg = "#5EB1AF" })
h(0, "diffLine", { fg = "#84848C" })
h(0, "diffFile", { fg = "#7AA8CE" })
h(0, "diffNewFile", { fg = "#C79A76" })
h(0, "diffOldFile", { fg = "#C7B96F" })
h(0, "diffChanged", { fg = "#7AA8CE" })
h(0, "SagaInCurrent", { fg = "#C79A76" })
h(0, "CopilotSuggestion", { fg = "#84848C" })
h(0, "NeoTreeRootName", { bold = true, fg = "#7AA8CE" })
h(0, "BlinkCmpKindMethod", { fg = "#7AA8CE" })
h(0, "DropBarKindFunction", { fg = "#A2A2A9" })
h(0, "BlinkCmpKindEnumMember", { fg = "#5EB1AF" })
h(0, "BlinkCmpKindEvent", { fg = "#7AA8CE" })
h(0, "SagaFolderName", { bold = true, fg = "#7D7D7D" })
h(0, "BlinkPairsMatchParen", { link = "MatchParen" })
h(0, "SagaSearch", { link = "Search" })
h(0, "SagaCount", { fg = "#808084" })
h(0, "NvimTreeFolderName", { fg = "#7AA8CE" })
h(0, "Statement", { fg = "#A19DD4" })
h(0, "Identifier", { fg = "#C394C2" })
h(0, "Character", { fg = "#5EB1AF" })
h(0, "Special", { fg = "#A19DD4" })
h(0, "NeotestAdapterName", { fg = "#DF8BA0" })
h(0, "NeotestWinSelect", { bold = true, fg = "#7AA8CE" })
h(0, "NeotestMarked", { bold = true, fg = "#C79A76" })
h(0, "NeotestTarget", { fg = "#DF8BA0" })
h(0, "NeotestUnknown", { fg = "#A2A2A9" })
h(0, "SpecialComment", { link = "Special" })
h(0, "@type.tag.css", { fg = "#7AA8CE" })
h(0, "@type.css", { fg = "#7AA8CE" })
h(0, "DropBarKindNumber", { fg = "#A2A2A9" })
h(0, "LineNr", { fg = "#7C7992" })
h(0, "OctoUser", { link = "OctoBubble" })
h(0, "OctoFailingTest", { link = "OctoRed" })
h(0, "OperatorSandwichAdd", { bg = "#7AA8CE", fg = "#191724" })
h(0, "OperatorSandwichDelete", { bg = "#7AA8CE", fg = "#191724" })
h(0, "OctoGreyFloat", { bg = "#191724", fg = "#A2A2A9" })
h(0, "NoiceCmdline", { fg = "#A2A2A9" })
h(0, "NoiceCmdlineIcon", { italic = true, fg = "#5EB1AF" })
h(0, "NoiceCmdlineIconSearch", { fg = "#C7B96F" })
h(0, "NoiceCmdlinePopupBorder", { fg = "#7AA8CE" })
h(0, "NoiceCmdlinePopupBorderSearch", { fg = "#C7B96F" })
h(0, "NoiceConfirmBorder", { fg = "#7AA8CE" })
h(0, "NoiceMini", { blend = 0, fg = "#878794" })
h(0, "NoiceFormatProgressDone", { bg = "#2E454E", fg = "#878794" })
h(0, "NoiceFormatProgressTodo", { bg = "#2C2B35", fg = "#878794" })
h(0, "OctoUserViewer", { link = "OctoViewer" })
h(0, "BlinkCmpMenuSelection", { bg = "#37363E", bold = true })
h(0, "OctoPurpleFloat", { bg = "#191724", fg = "#A19DD4" })
h(0, "OctoStateClosedFloat", { bg = "#191724", fg = "#DF8BA0" })
h(0, "DashboardShortCut", { fg = "#A19DD4" })
h(0, "DashboardHeader", { fg = "#7AA8CE" })
h(0, "DashboardCenter", { fg = "#75B087" })
h(0, "DashboardFooter", { italic = true, fg = "#C7B96F" })
h(0, "DashboardMruTitle", { fg = "#5EB1AF" })
h(0, "Error", { fg = "#DF8BA0" })
h(0, "NotifierIcon", { fg = "#A19DD4" })
h(0, "NotifierContent", { italic = true, blend = 0, fg = "#7D7D7D" })
h(0, "NotifierContentDim", { italic = true, blend = 0, fg = "#808084" })
h(0, "DashboardFiles", { fg = "#7AA8CE" })
h(0, "DashboardKey", { fg = "#C79A76" })
h(0, "NvimTreeImageFile", { fg = "#A2A2A9" })
h(0, "NvimTreeOpenedFile", { fg = "#A19DD4" })
h(0, "DapUIStepOut", { fg = "#7AA8CE" })
h(0, "FernBranchText", { fg = "#7AA8CE" })
h(0, "DapUIBreakpointsDisabledLine", { fg = "#7C7992" })
h(0, "DapUIWatchesEmpty", { fg = "#DF8BA0" })
h(0, "CmpItemAbbr", { fg = "#7D7D7D" })
h(0, "CmpItemAbbrDeprecated", { strikethrough = true, fg = "#84848C" })
h(0, "CmpItemKind", { fg = "#7AA8CE" })
h(0, "CmpItemMenu", { fg = "#A2A2A9" })
h(0, "CmpItemAbbrMatch", { bold = true, fg = "#A2A2A9" })
h(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#A2A2A9" })
h(0, "CmpItemKindSnippet", { fg = "#A19DD4" })
h(0, "CmpItemKindKeyword", { fg = "#DF8BA0" })
h(0, "CmpItemKindText", { fg = "#5EB1AF" })
h(0, "CmpItemKindMethod", { fg = "#7AA8CE" })
h(0, "CmpItemKindConstructor", { fg = "#7AA8CE" })
h(0, "CmpItemKindFunction", { fg = "#7AA8CE" })
h(0, "CmpItemKindFolder", { fg = "#7AA8CE" })
h(0, "CmpItemKindModule", { fg = "#7AA8CE" })
h(0, "CmpItemKindConstant", { fg = "#C79A76" })
h(0, "CmpItemKindField", { fg = "#75B087" })
h(0, "CmpItemKindProperty", { fg = "#75B087" })
h(0, "CmpItemKindEnum", { fg = "#75B087" })
h(0, "CmpItemKindUnit", { fg = "#75B087" })
h(0, "CmpItemKindClass", { fg = "#C7B96F" })
h(0, "CmpItemKindVariable", { fg = "#C394C2" })
h(0, "CmpItemKindFile", { fg = "#7AA8CE" })
h(0, "CmpItemKindInterface", { fg = "#C7B96F" })
h(0, "CmpItemKindColor", { fg = "#DF8BA0" })
h(0, "CmpItemKindReference", { fg = "#DF8BA0" })
h(0, "CmpItemKindEnumMember", { fg = "#DF8BA0" })
h(0, "CmpItemKindStruct", { fg = "#7AA8CE" })
h(0, "CmpItemKindValue", { fg = "#C79A76" })
h(0, "CmpItemKindEvent", { fg = "#7AA8CE" })
h(0, "CmpItemKindOperator", { fg = "#7AA8CE" })
h(0, "DropBarKindObject", { fg = "#A2A2A9" })
h(0, "CmpItemKindCopilot", { fg = "#5EB1AF" })
h(0, "DropBarKindOperator", { fg = "#A2A2A9" })
h(0, "SagaFileName", { bold = true, fg = "#7D7D7D" })
h(0, "DropBarKindPackage", { fg = "#A2A2A9" })
h(0, "OctoStatePending", { bg = "#191724", fg = "#C79A76" })
h(0, "DropBarKindProperty", { fg = "#A2A2A9" })
h(0, "NeogitPopupSwitchKey", { fg = "#7AA8CE" })
h(0, "DropBarKindReference", { fg = "#A2A2A9" })
h(0, "NeogitPopupOptionKey", { fg = "#7AA8CE" })
h(0, "DropBarKindRepeat", { fg = "#A2A2A9" })
h(0, "FlashBackdrop", { fg = "#84848C" })
h(0, "DropBarKindScope", { fg = "#A2A2A9" })
h(0, "LightspeedLabelDistant", { bold = true, underline = true, fg = "#5EB1AF" })
h(0, "LightspeedShortcut", { bg = "#df4269", bold = true, fg = "#ffffff" })
h(0, "LightspeedMaskedChar", { fg = "#78759F" })
h(0, "LightspeedUnlabeledMatch", { bold = true, fg = "#A2A2A9" })
h(0, "LightspeedGreyWash", { link = "Comment" })
h(0, "LightspeedUniqueChar", { link = "LightspeedUnlabeledMatch" })
h(0, "LightspeedOneCharMatch", { link = "LightspeedShortcut" })
h(0, "LightspeedPendingOpArea", { link = "IncSearch" })
h(0, "LightspeedCursor", { link = "Cursor" })
h(0, "DapUIValue", { fg = "#5EB1AF" })
h(0, "FlashMatch", { bg = "#191724", fg = "#7AA8CE" })
h(0, "FlashCurrent", { bg = "#191724", fg = "#C79A76" })
h(0, "DapUIDecoration", { fg = "#5EB1AF" })
h(0, "DapUIStepInto", { fg = "#7AA8CE" })
h(0, "DapUIStepIntoNC", { link = "DapUIStepInto" })
h(0, "GitSignsChange", { fg = "#C7B96F" })
h(0, "OctoDiffHunkPosition", { link = "NormalFloat" })
h(0, "OctoCommentLine", { link = "TabLineSel" })
h(0, "BlinkIndentCyan", { fg = "#5EB1AF" })
h(0, "BlinkIndentBlue", { fg = "#7AA8CE" })
h(0, "BlinkIndentViolet", { fg = "#A19DD4" })
h(0, "BlinkIndentRedUnderline", { sp = "#DF8BA0", underline = true })
h(0, "BlinkIndentOrangeUnderline", { sp = "#C79A76", underline = true })
h(0, "BlinkIndentYellowUnderline", { sp = "#C7B96F", underline = true })
h(0, "BlinkIndentGreenUnderline", { sp = "#75B087", underline = true })
h(0, "BlinkIndentCyanUnderline", { sp = "#5EB1AF", underline = true })
h(0, "BlinkIndentBlueUnderline", { sp = "#7AA8CE", underline = true })
h(0, "BlinkIndentVioletUnderline", { sp = "#A19DD4", underline = true })
h(0, "OctoViewer", { bg = "#7AA8CE", fg = "#191724" })
h(0, "OctoBubble", { bg = "#191724", fg = "#A2A2A9" })
h(0, "@keyword.conditional", { link = "Conditional" })
h(0, "@keyword.conditional.ternary", { link = "Operator" })
h(0, "@keyword.directive", { link = "PreProc" })
h(0, "@keyword.directive.define", { link = "Define" })
h(0, "SagaTitle", { bold = true, fg = "#5EB1AF" })
h(0, "SagaBorder", { bg = "NONE", fg = "#7AA8CE" })
h(0, "SagaNormal", { bg = "#191724" })
h(0, "SagaToggle", { fg = "#75B087" })
h(0, "BlinkPairsRed", { fg = "#DF8BA0" })
h(0, "BlinkPairsYellow", { fg = "#C7B96F" })
h(0, "BlinkPairsBlue", { fg = "#7AA8CE" })
h(0, "BlinkPairsOrange", { fg = "#C79A76" })
h(0, "BlinkPairsGreen", { fg = "#75B087" })
h(0, "BlinkPairsPurple", { fg = "#A19DD4" })
h(0, "BlinkPairsCyan", { fg = "#5EB1AF" })
h(0, "BlinkPairsUnmatched", { fg = "#DF8BA0" })
h(0, "SagaFinderFname", { bold = true, fg = "#878794" })
h(0, "ActionFix", { fg = "#A19DD4" })
h(0, "ActionPreviewTitle", { bg = "#191724", fg = "#A19DD4" })
h(0, "CodeActionText", { fg = "#75B087" })
h(0, "CodeActionNumber", { fg = "#A19DD4" })
h(0, "SagaImpIcon", { fg = "#A19DD4" })
h(0, "SagaLightBulb", { link = "DiagnosticSignHint" })
h(0, "RenameNormal", { fg = "#A2A2A9" })
h(0, "RenameMatch", { link = "Search" })
h(0, "DiagnosticText", { fg = "#A2A2A9" })
h(0, "SagaWinbarSep", { fg = "#C394C2" })
h(0, "BuffonUnloadedBuffer", { fg = "#37363E" })
h(0, "BuffonShortcut", { fg = "#C79A76" })
h(0, "BuffonLineActive", { fg = "#5EB1AF" })
h(0, "BuffonUnsavedIndicator", { fg = "#DF8BA0" })
h(0, "LspKindClass", { fg = "#C7B96F" })
h(0, "LspKindConstant", { fg = "#C79A76" })
h(0, "LspKindConstructor", { fg = "#5EB1AF" })
h(0, "LspKindEnum", { fg = "#C7B96F" })
h(0, "LspKindEnumMember", { fg = "#5EB1AF" })
h(0, "LspKindEvent", { fg = "#C7B96F" })
h(0, "LspKindField", { fg = "#5EB1AF" })
h(0, "LspKindFile", { fg = "#C394C2" })
h(0, "LspKindFunction", { fg = "#7AA8CE" })
h(0, "LspKindInterface", { fg = "#C7B96F" })
h(0, "LspKindKey", { fg = "#DF8BA0" })
h(0, "LspKindMethod", { fg = "#7AA8CE" })
h(0, "LspKindModule", { fg = "#7AA8CE" })
h(0, "LspKindNamespace", { fg = "#7AA8CE" })
h(0, "LspKindNumber", { fg = "#C79A76" })
h(0, "LspKindOperator", { fg = "#5EB1AF" })
h(0, "LspKindPackage", { fg = "#7AA8CE" })
h(0, "LspKindProperty", { fg = "#5EB1AF" })
h(0, "LspKindStruct", { fg = "#C7B96F" })
h(0, "LspKindTypeParameter", { fg = "#7AA8CE" })
h(0, "LspKindVariable", { fg = "#C79A76" })
h(0, "LspKindArray", { fg = "#C79A76" })
h(0, "LspKindBoolean", { fg = "#C79A76" })
h(0, "LspKindNull", { fg = "#C7B96F" })
h(0, "LspKindObject", { fg = "#C7B96F" })
h(0, "LspKindString", { fg = "#75B087" })
h(0, "LspKindTypeAlias", { fg = "#75B087" })
h(0, "LspKindParameter", { fg = "#7AA8CE" })
h(0, "LspKindStaticMethod", { fg = "#C79A76" })
h(0, "LspKindText", { fg = "#75B087" })
h(0, "LspKindSnippet", { fg = "#A19DD4" })
h(0, "LspKindFolder", { fg = "#7AA8CE" })
h(0, "LspKindUnit", { fg = "#75B087" })
h(0, "LspKindValue", { fg = "#C79A76" })
h(0, "@keyword.export", { fg = "#A19DD4" })
h(0, "@punctuation.delimiter", { link = "Delimiter" })
h(0, "@punctuation.bracket", { fg = "#7D7D7D" })
h(0, "@punctuation.special", { link = "Special" })
h(0, "@comment", { link = "Comment" })
h(0, "@comment.documentation", { link = "Comment" })
h(0, "@comment.error", { bg = "#DF8BA0", fg = "#191724" })
h(0, "@comment.warning", { bg = "#C7B96F", fg = "#191724" })
h(0, "@comment.hint", { bg = "#7AA8CE", fg = "#191724" })
h(0, "@comment.todo", { bg = "#C394C2", fg = "#191724" })
h(0, "@comment.note", { bg = "#7AA8CE", fg = "#191724" })
h(0, "@markup", { fg = "#A2A2A9" })
h(0, "@markup.strong", { bold = true, fg = "#DF8BA0" })
h(0, "@markup.italic", { italic = true, fg = "#DF8BA0" })
h(0, "@markup.strikethrough", { strikethrough = true, fg = "#A2A2A9" })
h(0, "OctoBubbleGrey", { bg = "#191724", fg = "#A2A2A9" })
h(0, "@markup.underline", { link = "Underlined" })
h(0, "@markup.heading", { fg = "#7AA8CE" })
h(0, "@markup.heading.markdown", { bold = true })
h(0, "@markup.math", { fg = "#7AA8CE" })
h(0, "@markup.quote", { fg = "#A19DD4" })
h(0, "@markup.environment", { fg = "#A19DD4" })
h(0, "@markup.environment.name", { fg = "#7AA8CE" })
h(0, "@markup.link", { fg = "#7AA8CE" })
h(0, "@markup.link.label", { fg = "#7AA8CE" })
h(0, "@markup.link.url", { italic = true, underline = true, fg = "#7AA8CE" })
h(0, "@markup.raw", { fg = "#75B087" })
h(0, "@markup.list", { fg = "#5EB1AF" })
h(0, "@markup.list.checked", { fg = "#75B087" })
h(0, "@markup.list.unchecked", { fg = "#808084" })
h(0, "@diff.plus", { link = "diffAdded" })
h(0, "@diff.minus", { link = "diffRemoved" })
h(0, "@diff.delta", { link = "diffChanged" })
h(0, "@tag", { fg = "#7AA8CE" })
h(0, "@tag.builtin", { fg = "#7AA8CE" })
h(0, "@tag.attribute", { italic = true, fg = "#C7B96F" })
h(0, "@tag.delimiter", { fg = "#5EB1AF" })
h(0, "@error", { link = "Error" })
h(0, "@function.builtin.bash", { italic = true, fg = "#DF8BA0" })
h(0, "@variable.parameter.bash", { fg = "#75B087" })
h(0, "@markup.heading.1.markdown", { link = "rainbow1" })
h(0, "@markup.heading.2.markdown", { link = "rainbow2" })
h(0, "@markup.heading.3.markdown", { link = "rainbow3" })
h(0, "@markup.heading.4.markdown", { link = "rainbow4" })
h(0, "@markup.heading.5.markdown", { link = "rainbow5" })
h(0, "@markup.heading.6.markdown", { link = "rainbow6" })
h(0, "@markup.heading.html", { link = "@markup" })
h(0, "@markup.heading.1.html", { link = "@markup" })
h(0, "@markup.heading.2.html", { link = "@markup" })
h(0, "@markup.heading.3.html", { link = "@markup" })
h(0, "@markup.heading.4.html", { link = "@markup" })
h(0, "@markup.heading.5.html", { link = "@markup" })
h(0, "@markup.heading.6.html", { link = "@markup" })
h(0, "@constant.java", { fg = "#5EB1AF" })
h(0, "@property.css", { fg = "#7AA8CE" })
h(0, "@property.scss", { fg = "#7AA8CE" })
h(0, "@property.id.css", { fg = "#C7B96F" })
h(0, "@property.class.css", { fg = "#C7B96F" })
h(0, "TroubleText", { fg = "#75B087" })
h(0, "TroubleCount", { bg = "#37363E", fg = "#A19DD4" })
h(0, "TroubleNormal", { bg = "#0B0A0F", fg = "#A2A2A9" })
h(0, "TroubleNormalNC", { link = "TroubleNormal" })
h(0, "@keyword.directive.css", { link = "Keyword" })
h(0, "@string.special.url.html", { fg = "#75B087" })
h(0, "@markup.link.label.html", { fg = "#A2A2A9" })
h(0, "@character.special.html", { fg = "#DF8BA0" })
h(0, "@constructor.lua", { link = "@punctuation.bracket" })
h(0, "@constructor.python", { fg = "#5EB1AF" })
h(0, "Exception", { fg = "#A19DD4" })
h(0, "@string.special.symbol.ruby", { fg = "#C394C2" })
h(0, "@function.method.php", { link = "Function" })
h(0, "@function.method.call.php", { link = "Function" })
h(0, "DropBarKindSpecifier", { fg = "#A2A2A9" })
h(0, "@keyword.import.cpp", { fg = "#C7B96F" })
h(0, "DropBarKindStatement", { fg = "#A2A2A9" })
h(0, "@comment.warning.gitcommit", { fg = "#C7B96F" })
h(0, "@string.special.path.gitignore", { fg = "#A2A2A9" })
h(0, "gitcommitSummary", { italic = true, fg = "#C394C2" })
h(0, "zshKSHFunction", { link = "Function" })
h(0, "@parameter", { fg = "#DF8BA0" })
h(0, "@field", { fg = "#7AA8CE" })
h(0, "@namespace", { italic = true, fg = "#C7B96F" })
h(0, "@float", { link = "Float" })
h(0, "@symbol", { fg = "#C394C2" })
h(0, "@string.regex", { fg = "#A19DD4" })
h(0, "@text", { fg = "#A2A2A9" })
h(0, "@text.strong", { bold = true, fg = "#DF8BA0" })
h(0, "@text.emphasis", { italic = true, fg = "#DF8BA0" })
h(0, "@text.underline", { link = "Underlined" })
h(0, "@text.strike", { strikethrough = true, fg = "#A2A2A9" })
h(0, "DapUIStepOver", { fg = "#7AA8CE" })
h(0, "@text.math", { fg = "#7AA8CE" })
h(0, "@text.environment", { fg = "#A19DD4" })
h(0, "@text.environment.name", { fg = "#7AA8CE" })
h(0, "@text.title", { fg = "#7AA8CE" })
h(0, "@text.literal", { fg = "#75B087" })
h(0, "@text.reference", { fg = "#7AA8CE" })
h(0, "@text.todo.checked", { fg = "#75B087" })
h(0, "@text.todo.unchecked", { fg = "#808084" })
h(0, "@text.todo", { bg = "#C394C2", fg = "#191724" })
h(0, "@text.warning", { bg = "#C7B96F", fg = "#191724" })
h(0, "@text.note", { bg = "#7AA8CE", fg = "#191724" })
h(0, "@text.danger", { bg = "#DF8BA0", fg = "#191724" })
h(0, "NavicIconsFile", { bg = "NONE", fg = "#7AA8CE" })
h(0, "@method", { link = "Function" })
h(0, "@method.call", { link = "Function" })
h(0, "@text.diff.add", { link = "diffAdded" })
h(0, "@text.diff.delete", { link = "diffRemoved" })
h(0, "@type.qualifier", { link = "Keyword" })
h(0, "@keyword.storage", { link = "Keyword" })
h(0, "@define", { link = "Define" })
h(0, "@preproc", { link = "PreProc" })
h(0, "@storageclass", { link = "Keyword" })
h(0, "@conditional", { link = "Conditional" })
h(0, "@exception", { link = "Exception" })
h(0, "@include", { link = "Include" })
h(0, "@repeat", { link = "Repeat" })
h(0, "@symbol.ruby", { fg = "#C394C2" })
h(0, "DapUIWatchesError", { fg = "#DF8BA0" })
h(0, "DapUIWatchesValue", { fg = "#75B087" })
h(0, "@text.title.1.markdown", { link = "rainbow1" })
h(0, "AerialLine", { bg = "NONE", fg = "#C7B96F" })
h(0, "AerialGuide", { fg = "#7D7D7D" })
h(0, "AerialBooleanIcon", { link = "@boolean" })
h(0, "AerialClassIcon", { link = "@type" })
h(0, "AerialConstantIcon", { link = "@constant" })
h(0, "AerialConstructorIcon", { link = "@constructor" })
h(0, "AerialFieldIcon", { link = "@field" })
h(0, "AerialFunctionIcon", { link = "@function" })
h(0, "AerialMethodIcon", { link = "@method" })
h(0, "AerialNamespaceIcon", { link = "@namespace" })
h(0, "AerialNumberIcon", { link = "@number" })
h(0, "AerialOperatorIcon", { link = "@operator" })
h(0, "AerialTypeParameterIcon", { link = "@type" })
h(0, "AerialPropertyIcon", { link = "@property" })
h(0, "AerialStringIcon", { link = "@string" })
h(0, "AerialVariableIcon", { link = "@constant" })
h(0, "AerialEnumMemberIcon", { link = "@field" })
h(0, "DiffviewDim1", { link = "Comment" })
h(0, "DiffviewPrimary", { fg = "#7AA8CE" })
h(0, "AerialModuleIcon", { link = "@namespace" })
h(0, "AerialPackageIcon", { link = "@namespace" })
h(0, "DiffviewWinSeparator", { bg = "#191724", fg = "#191724" })
h(0, "DiffviewFilePanelTitle", { bold = true, fg = "#7AA8CE" })
h(0, "AerialEventIcon", { link = "@type" })
h(0, "AerialArrayIcon", { link = "@constant" })
h(0, "DiffviewFilePanelFileName", { fg = "#A2A2A9" })
h(0, "DiffviewFilePanelSelected", { fg = "#C7B96F" })
h(0, "DiffviewFilePanelPath", { link = "Comment" })
h(0, "DiffviewFilePanelInsertions", { fg = "#75B087" })
h(0, "DiffviewFilePanelDeletions", { fg = "#DF8BA0" })
h(0, "DiffviewFilePanelConflicts", { fg = "#C7B96F" })
h(0, "DiffviewFolderName", { bold = true, fg = "#7AA8CE" })
h(0, "DiffviewFolderSign", { fg = "#7AA8CE" })
h(0, "DiffviewHash", { fg = "#C394C2" })
h(0, "DiffviewReference", { bold = true, fg = "#7AA8CE" })
h(0, "DiffviewReflogSelector", { fg = "#A19DD4" })
h(0, "DiffviewStatusAdded", { fg = "#75B087" })
h(0, "DiffviewStatusUntracked", { fg = "#75B087" })
h(0, "AlphaShortcut", { fg = "#75B087" })
h(0, "AlphaHeader", { fg = "#7AA8CE" })
h(0, "AlphaHeaderLabel", { fg = "#C79A76" })
h(0, "DiffviewStatusTypeChange", { fg = "#C7B96F" })
h(0, "AlphaFooter", { italic = true, fg = "#C7B96F" })
h(0, "DiffviewStatusUnknown", { fg = "#DF8BA0" })
h(0, "DiffviewStatusDeleted", { fg = "#DF8BA0" })
h(0, "DiffviewStatusBroken", { fg = "#DF8BA0" })
h(0, "DiffviewStatusIgnored", { fg = "#84848C" })
h(0, "OctoBlueFloat", { bg = "#191724", fg = "#7AA8CE" })
h(0, "OctoFilePanelCounter", { bold = true, fg = "#7AA8CE" })
h(0, "OperatorSandwichChange", { bg = "#7AA8CE", fg = "#191724" })
h(0, "OperatorSandwichBuns", { bg = "#7AA8CE", fg = "#191724" })
h(0, "SagaSpinnerTitle", { bold = true, fg = "#A19DD4" })
h(0, "SagaText", { fg = "#A2A2A9" })
h(0, "ArtioNormal", { bg = "#0B0A0F", fg = "#A2A2A9" })
h(0, "ArtioSel", { bg = "#37363E", bold = true, fg = "#C394C2" })
h(0, "ArtioMatch", { fg = "#7AA8CE" })
h(0, "ArtioPointer", { fg = "#C394C2" })
h(0, "ArtioPrompt", { fg = "#7AA8CE" })
h(0, "ArtioMark", { fg = "#C7B96F" })
h(0, "ArtioMarkLine", { link = "Visual" })
h(0, "SagaBeacon", { bg = "#2E2D35" })
h(0, "SagaVirtLine", { fg = "#7C7992" })
h(0, "SagaSpinner", { bold = true, fg = "#A19DD4" })
h(0, "NvimTreeNormal", { bg = "#0B0A0F", fg = "#A2A2A9" })
h(0, "NvimTreeFolderIcon", { fg = "#7AA8CE" })
h(0, "SagaSelect", { bold = true, fg = "#7AA8CE" })
h(0, "OctoReviewDiffAddText", { bg = "#354542" })
h(0, "OctoPullAdditions", { link = "OctoGreen" })
h(0, "BlinkCmpKindSnippet", { fg = "#C394C2" })
h(0, "DapUIType", { fg = "#A19DD4" })
h(0, "BufferCurrent", { bg = "#37363E", fg = "#A2A2A9" })
h(0, "BufferCurrentIndex", { bg = "#37363E", fg = "#7AA8CE" })
h(0, "NavicIconsNamespace", { bg = "NONE", fg = "#7AA8CE" })
h(0, "NavicIconsPackage", { bg = "NONE", fg = "#7AA8CE" })
h(0, "NavicIconsClass", { bg = "NONE", fg = "#C7B96F" })
h(0, "BufferVisible", { bg = "#0B0A0F", fg = "#A2A2A9" })
h(0, "BufferVisibleIndex", { bg = "#0B0A0F", fg = "#7AA8CE" })
h(0, "NavicIconsField", { bg = "NONE", fg = "#75B087" })
h(0, "NavicIconsConstructor", { bg = "NONE", fg = "#7AA8CE" })
h(0, "NavicIconsEnum", { bg = "NONE", fg = "#75B087" })
h(0, "NavicIconsInterface", { bg = "NONE", fg = "#C7B96F" })
h(0, "NavicIconsFunction", { bg = "NONE", fg = "#7AA8CE" })
h(0, "NavicIconsVariable", { bg = "NONE", fg = "#C394C2" })
h(0, "BufferInactiveSign", { bg = "#0B0A0F", fg = "#7AA8CE" })
h(0, "NavicIconsString", { bg = "NONE", fg = "#75B087" })
h(0, "NavicIconsNumber", { bg = "NONE", fg = "#C79A76" })
h(0, "NavicIconsBoolean", { bg = "NONE", fg = "#C79A76" })
h(0, "NavicIconsArray", { bg = "NONE", fg = "#C79A76" })
h(0, "NavicIconsObject", { bg = "NONE", fg = "#C79A76" })
h(0, "NavicIconsKey", { bg = "NONE", fg = "#A19DD4" })
h(0, "NavicIconsNull", { bg = "NONE", fg = "#C79A76" })
h(0, "NavicIconsEnumMember", { bg = "NONE", fg = "#DF8BA0" })
h(0, "NavicIconsStruct", { bg = "NONE", fg = "#7AA8CE" })
h(0, "NavicIconsEvent", { bg = "NONE", fg = "#7AA8CE" })
h(0, "NavicIconsOperator", { bg = "NONE", fg = "#5EB1AF" })
h(0, "NavicIconsTypeParameter", { bg = "NONE", fg = "#7AA8CE" })
h(0, "NavicText", { bg = "NONE", fg = "#5EB1AF" })
h(0, "NavicSeparator", { bg = "NONE", fg = "#A2A2A9" })
h(0, "BlinkCmpKindReference", { fg = "#DF8BA0" })
h(0, "SignColumn", { fg = "#7C7992" })
h(0, "OctoPassingTest", { link = "OctoGreen" })
h(0, "SignColumnSB", { bg = "#0B0A0F", fg = "#7C7992" })
h(0, "TreesitterContextLineNumber", { bg = "#0B0A0F", fg = "#7C7992" })
h(0, "CursorLineNr", { fg = "#7AA8CE" })
h(0, "BlinkCmpKindConstant", { fg = "#C79A76" })
h(0, "OctoStateMerged", { bg = "#191724", fg = "#A19DD4" })
h(0, "BlinkCmpKindOperator", { fg = "#5EB1AF" })
h(0, "OctoStateMergedFloat", { bg = "#191724", fg = "#A19DD4" })
h(0, "BlinkCmpKind", { fg = "#7AA8CE" })
h(0, "BlinkCmpMenu", { link = "Pmenu" })
h(0, "NeoTreeDirectoryIcon", { fg = "#7AA8CE" })
h(0, "NeoTreeNormal", { bg = "#0B0A0F", fg = "#A2A2A9" })
h(0, "NeoTreeNormalNC", { bg = "#0B0A0F", fg = "#A2A2A9" })
h(0, "NeoTreeExpander", { fg = "#84848C" })
h(0, "BlinkCmpSignatureHelpBorder", { link = "FloatBorder" })
h(0, "BlinkCmpKindText", { fg = "#75B087" })
h(0, "NeoTreeSymbolicLinkTarget", { fg = "#A19DD4" })
h(0, "BlinkCmpKindFunction", { fg = "#7AA8CE" })
h(0, "NeoTreeGitAdded", { fg = "#75B087" })
h(0, "NeoTreeGitConflict", { fg = "#DF8BA0" })
h(0, "BlinkCmpKindVariable", { fg = "#C394C2" })
h(0, "NeoTreeGitIgnored", { fg = "#84848C" })
h(0, "BlinkCmpKindInterface", { fg = "#C7B96F" })
h(0, "NeoTreeGitUnstaged", { fg = "#DF8BA0" })
h(0, "BlinkCmpKindProperty", { fg = "#7AA8CE" })
h(0, "NeoTreeGitStaged", { fg = "#75B087" })
h(0, "BlinkCmpKindValue", { fg = "#C79A76" })
h(0, "BlinkCmpKindEnum", { fg = "#C7B96F" })
h(0, "BlinkCmpKindKeyword", { fg = "#A19DD4" })
h(0, "NeoTreeFileNameOpened", { fg = "#A19DD4" })
h(0, "NeoTreeDimText", { fg = "#808084" })
h(0, "NeoTreeFilterTerm", { bold = true, fg = "#75B087" })
h(0, "NeoTreeTabActive", { bg = "#0B0A0F", bold = true, fg = "#7AA8CE" })
h(0, "BlinkCmpKindFolder", { fg = "#7AA8CE" })
h(0, "NeoTreeTabSeparatorActive", { bg = "#0B0A0F", fg = "#0B0A0F" })
h(0, "NeoTreeTabSeparatorInactive", { bg = "#191724", fg = "#191724" })
h(0, "BlinkCmpKindStruct", { fg = "#7AA8CE" })
h(0, "NeoTreeWinSeparator", { bg = "#191724", fg = "#191724" })
h(0, "NeoTreeStatusLineNC", { bg = "#0B0A0F", fg = "#0B0A0F" })
h(0, "BlinkCmpKindTypeParameter", { fg = "#DF8BA0" })
h(0, "BlinkCmpKindCopilot", { fg = "#5EB1AF" })
h(0, "BlinkCmpMenuBorder", { bg = "#0B0A0F", fg = "#7AA8CE" })
h(0, "BlinkCmpDocBorder", { link = "FloatBorder" })
h(0, "BlinkIndent", { fg = "#37363E" })
h(0, "OctoStateClosed", { bg = "#191724", fg = "#DF8BA0" })
h(0, "BlinkIndentRed", { fg = "#DF8BA0" })
h(0, "OctoStateOpenFloat", { bg = "#191724", fg = "#75B087" })
h(0, "BlinkIndentYellow", { fg = "#C7B96F" })
h(0, "OctoReactionViewer", { link = "OctoViewer" })
h(0, "NeotestPassed", { fg = "#75B087" })
h(0, "NeotestFailed", { fg = "#DF8BA0" })
h(0, "NeotestRunning", { fg = "#C7B96F" })
h(0, "NeotestSkipped", { fg = "#7AA8CE" })
h(0, "NeotestTest", { fg = "#A2A2A9" })
h(0, "BlinkIndentScope", { fg = "#7D7D7D" })
h(0, "NeotestFocused", { underline = true, bold = true })
h(0, "BlinkIndentOrange", { fg = "#C79A76" })
h(0, "NeotestDir", { fg = "#7AA8CE" })
h(0, "BlinkIndentGreen", { fg = "#75B087" })
h(0, "NeotestExpandMarker", { fg = "#808084" })
h(0, "DropBarKindNull", { fg = "#A2A2A9" })
h(0, "OctoBubbleDelimiterPurple", { fg = "#A19DD4" })
h(0, "DapUIBreakpointsPath", { fg = "#5EB1AF" })
h(0, "OctoYellowFloat", { bg = "#191724", fg = "#C7B96F" })
h(0, "DapUIBreakpointsInfo", { fg = "#75B087" })
h(0, "DropBarKindString", { fg = "#A2A2A9" })
h(0, "OctoDirty", { link = "ErrorMsg" })
h(0, "DropBarKindStruct", { fg = "#A2A2A9" })
h(0, "NeotestIndent", { fg = "#808084" })
h(0, "DropBarKindSwitchStatement", { fg = "#A2A2A9" })
h(0, "NeotestFile", { fg = "#7AA8CE" })
h(0, "DropBarKindType", { fg = "#A2A2A9" })
h(0, "NeotestNamespace", { fg = "#A19DD4" })
h(0, "DropBarKindTypeParameter", { fg = "#A2A2A9" })
h(0, "DapUIModifiedValue", { fg = "#C79A76" })
h(0, "DropBarKindUnit", { fg = "#A2A2A9" })
h(0, "NeoTreeVertSplit", { bg = "#191724", fg = "#191724" })
h(0, "DropBarKindValue", { fg = "#A2A2A9" })
h(0, "NeoTreeTabInactive", { bg = "#191724", fg = "#84848C" })
h(0, "DropBarKindVariable", { fg = "#A2A2A9" })
h(0, "BlinkCmpKindColor", { fg = "#DF8BA0" })
h(0, "DropBarKindWhileStatement", { fg = "#A2A2A9" })
h(0, "NeoTreeTitleBar", { bg = "#7AA8CE", fg = "#0B0A0F" })
h(0, "NeoTreeFloatTitle", { link = "FloatTitle" })
h(0, "NeoTreeFloatBorder", { link = "FloatBorder" })
h(0, "BlinkCmpKindUnit", { fg = "#75B087" })
h(0, "NeoTreeGitUntracked", { fg = "#A19DD4" })
h(0, "NeoTreeGitModified", { fg = "#C7B96F" })
h(0, "BlinkCmpKindClass", { fg = "#C7B96F" })
h(0, "NeoTreeGitDeleted", { fg = "#DF8BA0" })
h(0, "BlinkCmpKindField", { fg = "#75B087" })
h(0, "BlinkCmpKindConstructor", { fg = "#7AA8CE" })
h(0, "NeoTreeModified", { fg = "#C79A76" })
h(0, "WinSeparator", { fg = "#7C7992" })
h(0, "PmenuSel", { bg = "#37363E", bold = true })
h(0, "NeoTreeIndentMarker", { fg = "#84848C" })
h(0, "BlinkCmpScrollBarThumb", { bg = "#84848C" })
h(0, "Pmenu", { bg = "#0B0A0F", fg = "#7D7D7D" })
h(0, "DapUIUnavailable", { fg = "#7C7992" })
h(0, "BlinkCmpDoc", { link = "NormalFloat" })
h(0, "NeoTreeDirectoryName", { fg = "#7AA8CE" })
h(0, "DropBarKindIdentifier", { fg = "#A2A2A9" })
h(0, "SnacksIndent", { fg = "#37363E" })
h(0, "BufferTabpage", { bg = "#0B0A0F", fg = "#7AA8CE" })
h(0, "BufferTabpages", { bg = "#0B0A0F", fg = "NONE" })
h(0, "BufferInactiveTarget", { bg = "#0B0A0F", fg = "#DF8BA0" })
h(0, "NavicIconsConstant", { bg = "NONE", fg = "#C79A76" })
h(0, "BufferInactiveMod", { bg = "#0B0A0F", fg = "#C7B96F" })
h(0, "BufferInactiveIndex", { bg = "#0B0A0F", fg = "#84848C" })
h(0, "Directory", { fg = "#7AA8CE" })
h(0, "BufferVisibleTarget", { bg = "#0B0A0F", fg = "#DF8BA0" })
h(0, "BufferVisibleSign", { bg = "#0B0A0F", fg = "#7AA8CE" })
h(0, "BufferVisibleMod", { bg = "#0B0A0F", fg = "#C7B96F" })
h(0, "NavicIconsProperty", { bg = "NONE", fg = "#75B087" })
h(0, "NavicIconsMethod", { bg = "NONE", fg = "#7AA8CE" })
h(0, "BufferCurrentTarget", { bg = "#37363E", fg = "#DF8BA0" })
h(0, "BufferCurrentSign", { bg = "#37363E", fg = "#7AA8CE" })
h(0, "IblScope", { fg = "#A2A2A9" })
h(0, "IblIndent", { fg = "#37363E" })
h(0, "AerialObjectIcon", { link = "@type" })
h(0, "ColorColumn", { bg = "#37363E" })
h(0, "Conceal", { fg = "#808084" })
h(0, "Cursor", { bg = "#C394C2", fg = "#191724" })
h(0, "lCursor", { bg = "#C394C2", fg = "#191724" })
h(0, "CursorIM", { bg = "#C394C2", fg = "#191724" })
h(0, "CursorColumn", { bg = "#0B0A0F" })
h(0, "CursorLine", { bg = "#2C2B35" })
h(0, "Dimmed", { fg = "#808084" })
h(0, "EndOfBuffer", { fg = "#37363E" })
h(0, "NotifyBackground", { bg = "#0B0A0F" })
h(0, "NotifyERRORBorder", { fg = "#DF8BA0" })
h(0, "NotifyERRORIcon", { fg = "#DF8BA0" })
h(0, "NotifyERRORTitle", { italic = true, fg = "#DF8BA0" })
h(0, "NotifyWARNBorder", { fg = "#C7B96F" })
h(0, "NotifyWARNIcon", { fg = "#C7B96F" })
h(0, "NotifyWARNTitle", { italic = true, fg = "#C7B96F" })
h(0, "NotifyINFOBorder", { fg = "#7AA8CE" })
h(0, "NotifyINFOIcon", { fg = "#7AA8CE" })
h(0, "NotifyINFOTitle", { italic = true, fg = "#7AA8CE" })
h(0, "NotifyDEBUGBorder", { fg = "#C79A76" })
h(0, "CocMenuSel", { link = "PmenuSel" })
h(0, "CocPumSearch", { bold = true, fg = "#5EB1AF" })
h(0, "CocInlayHint", { italic = true, fg = "#84848C" })
h(0, "NotifyTRACEIcon", { fg = "#C394C2" })
h(0, "NotifyTRACETitle", { italic = true, fg = "#C394C2" })
h(0, "PmenuMatch", { bold = true, fg = "#A2A2A9" })
h(0, "PmenuMatchSel", { bold = true })
h(0, "PmenuSbar", { bg = "#37363E" })
h(0, "PmenuThumb", { bg = "#84848C" })
h(0, "PmenuExtra", { fg = "#84848C" })
h(0, "PmenuExtraSel", { bg = "#37363E", bold = true, fg = "#84848C" })
h(0, "ComplMatchIns", { link = "PreInsert" })
h(0, "PreInsert", { fg = "#7D7D7D" })
h(0, "NvimSurroundHighlight", { sp = "#C79A76", underline = true })
h(0, "CopilotAnnotation", { fg = "#7AA8CE" })
h(0, "NeogitBranch", { bold = true, fg = "#C79A76" })
h(0, "NeogitRemote", { bold = true, fg = "#75B087" })
h(0, "NeogitUnmergedInto", { link = "Function" })
h(0, "NeogitUnpulledFrom", { link = "Function" })
h(0, "NeogitObjectId", { link = "Comment" })
h(0, "NeogitStash", { link = "Comment" })
h(0, "NeogitRebaseDone", { link = "Comment" })
h(0, "NeogitHunkHeader", { bg = "#222534", fg = "#4A6079" })
h(0, "NeogitHunkHeaderHighlight", { bg = "#2E3649", fg = "#7AA8CE" })
h(0, "NeogitDiffContextHighlight", { bg = "#37363E" })
h(0, "NeogitDiffDeleteHighlight", { bg = "#5D3F4F", fg = "#D68EA1" })
h(0, "NeogitDiffAddHighlight", { bg = "#394C46", fg = "#7CAE8C" })
h(0, "NeogitDiffDelete", { bg = "#2C2230", fg = "#B77487" })
h(0, "NeogitDiffDeleteInline", { bg = "#7C5162", bold = true })
h(0, "NeogitDiffAdd", { bg = "#22262D", fg = "#639173" })
h(0, "NeogitDiffAddInline", { bg = "#476456", bold = true })
h(0, "NeogitCommitViewHeader", { bg = "#364357", fg = "#82A7C7" })
h(0, "NeogitChangeModified", { bold = true, fg = "#7AA8CE" })
h(0, "NeogitChangeDeleted", { bold = true, fg = "#DF8BA0" })
h(0, "NeogitChangeAdded", { bold = true, fg = "#75B087" })
h(0, "NeogitChangeRenamed", { bold = true, fg = "#A19DD4" })
h(0, "NeogitChangeUpdated", { bold = true, fg = "#C79A76" })
h(0, "NeogitChangeCopied", { bold = true, fg = "#A19DD4" })
h(0, "NeogitChangeBothModified", { bold = true, fg = "#C7B96F" })
h(0, "NeogitChangeNewFile", { bold = true, fg = "#75B087" })
h(0, "NeogitUntrackedfiles", { bold = true, fg = "#A19DD4" })
h(0, "NeogitUnstagedchanges", { bold = true, fg = "#A19DD4" })
h(0, "NeogitUnmergedchanges", { bold = true, fg = "#A19DD4" })
h(0, "NeogitUnpulledchanges", { bold = true, fg = "#A19DD4" })
h(0, "NeogitRecentcommits", { bold = true, fg = "#A19DD4" })
h(0, "NeogitStagedchanges", { bold = true, fg = "#A19DD4" })
h(0, "NeogitStashes", { bold = true, fg = "#A19DD4" })
h(0, "NeogitRebasing", { bold = true, fg = "#A19DD4" })
h(0, "NeogitNotificationInfo", { fg = "#7AA8CE" })
h(0, "NeogitNotificationWarning", { fg = "#C7B96F" })
h(0, "NeogitNotificationError", { fg = "#DF8BA0" })
h(0, "NeogitGraphRed", { fg = "#DF8BA0" })
h(0, "NeogitGraphWhite", { fg = "#191724" })
h(0, "NeogitGraphYellow", { fg = "#C7B96F" })
h(0, "NeogitGraphGreen", { fg = "#75B087" })
h(0, "NeogitGraphCyan", { fg = "#7AA8CE" })
h(0, "NeogitGraphBlue", { fg = "#7AA8CE" })
h(0, "NeogitGraphPurple", { fg = "#7AA8CE" })
h(0, "NeogitGraphGray", { fg = "#878794" })
h(0, "NeogitGraphOrange", { fg = "#C79A76" })
h(0, "NeogitGraphBoldRed", { bold = true, fg = "#DF8BA0" })
h(0, "NeogitGraphBoldWhite", { bold = true })
h(0, "NeogitGraphBoldYellow", { bold = true, fg = "#C7B96F" })
h(0, "NeogitGraphBoldGreen", { bold = true, fg = "#75B087" })
h(0, "NeogitGraphBoldCyan", { bold = true, fg = "#7AA8CE" })
h(0, "NeogitGraphBoldBlue", { bold = true, fg = "#7AA8CE" })
h(0, "NeogitGraphBoldPurple", { bold = true, fg = "#7AA8CE" })
h(0, "NeogitGraphBoldGray", { bold = true, fg = "#878794" })
h(0, "NeogitDiffContext", { bg = "#191724" })
h(0, "NeogitPopupBold", { bold = true })
h(0, "DashboardDesc", { fg = "#7AA8CE" })
h(0, "DashboardIcon", { bold = true, fg = "#A19DD4" })
h(0, "NeogitPopupConfigKey", { fg = "#7AA8CE" })
h(0, "NeogitPopupActionKey", { fg = "#7AA8CE" })
h(0, "NeogitFilePath", { italic = true, fg = "#7AA8CE" })
h(0, "NeogitDiffHeader", { bg = "#191724", bold = true, fg = "#7AA8CE" })
h(0, "NeogitDiffHeaderHighlight", { bg = "#191724", bold = true, fg = "#C79A76" })
h(0, "NeogitUnpushedTo", { bold = true, fg = "#7AA8CE" })
h(0, "NeogitFold", { bg = "NONE", fg = "NONE" })
h(0, "NeogitSectionHeader", { bold = true, fg = "#A19DD4" })
h(0, "NeogitTagName", { fg = "#C7B96F" })
h(0, "NeogitTagDistance", { fg = "#7AA8CE" })
h(0, "NeogitWinSeparator", { link = "WinSeparator" })
h(0, "DapUIStop", { fg = "#DF8BA0" })
h(0, "DapUIStopNC", { link = "DapUIStop" })
h(0, "DapUILineNumber", { fg = "#5EB1AF" })
h(0, "OctoYellow", { fg = "#C7B96F" })
h(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#75B087" })
h(0, "OctoGrey", { fg = "#191724" })
h(0, "OctoBlue", { fg = "#7AA8CE" })
h(0, "OctoGreen", { fg = "#75B087" })
h(0, "OctoRed", { fg = "#DF8BA0" })
h(0, "OctoPurple", { fg = "#A19DD4" })
h(0, "FidgetTask", { bg = "#0B0A0F", fg = "#A2A2A9" })
h(0, "FidgetTitle", { fg = "#7AA8CE" })
h(0, "OctoIssueTitle", { link = "PreProc" })
h(0, "OctoIssueId", { link = "Question" })
h(0, "OctoEmpty", { link = "Comment" })
h(0, "OctoFloat", { link = "NormalNC" })
h(0, "OctoDate", { link = "Comment" })
h(0, "OctoSymbol", { link = "Comment" })
h(0, "OctoTimelineItemHeading", { link = "Comment" })
h(0, "OctoDetailsLabel", { link = "Title" })
h(0, "OctoMissingDetails", { link = "Comment" })
h(0, "OctoDetailsValue", { link = "Identifier" })
h(0, "LeapMatch", { nocombine = true, underline = true, fg = "#89cd9e" })
h(0, "FlashLabel", { bg = "#191724", bold = true, fg = "#75B087" })
h(0, "LeapLabel", { bg = "#89cd9e", nocombine = true, fg = "#191724" })
h(0, "LeapBackdrop", { fg = "NONE" })
h(0, "FlashPrompt", { link = "NormalFloat" })
